export const ALL_QUESTIONS = [
  // --- 1. Путешествия ---
  {
    emoji: '✈️',
    category: 'Путешествия',
    question: 'Куда бы ты полетел прямо сейчас?',
    optionA: 'Тёплое море и пляж — только лежать',
    optionB: 'Тёплый курорт, но с экскурсиями',
    optionC: 'Горы с видами и лёгкими маршрутами',
    optionD: 'Экстремальный трекинг в горах',
    image: '/images/questions/q000.jpg',
  },
  {
    emoji: '🏕️',
    category: 'Путешествия',
    question: 'Идеальный отдых — это...',
    optionA: 'Палатка в лесу без связи',
    optionB: 'Глэмпинг с удобствами на природе',
    optionC: 'Уютный бутик-отель в горах',
    optionD: 'Отель 5 звёзд с бассейном',
    image: '/images/questions/q001.jpg',
  },
  {
    emoji: '🗺️',
    category: 'Путешествия',
    question: 'Как я планирую поездки?',
    optionA: 'Полная импровизация, билет в день вылета',
    optionB: 'Знаю направление, остальное по ходу',
    optionC: 'Маршрут готов, время гибкое',
    optionD: 'Всё расписано по часам и дням',
    image: '/images/questions/q002.jpg',
  },
  {
    emoji: '🌍',
    category: 'Путешествия',
    question: 'Переехать жить в другую страну?',
    optionA: 'Хоть завтра — мечтаю давно',
    optionB: 'Да, если будет хорошая возможность',
    optionC: 'Только временно, на пару лет',
    optionD: 'Нет, дома намного лучше',
    image: '/images/questions/q003.jpg',
  },
  {
    emoji: '🏙️',
    category: 'Путешествия',
    question: 'Где мне комфортнее жить?',
    optionA: 'Самый центр большого города',
    optionB: 'Спальный район с парком рядом',
    optionC: 'Тихий уютный пригород',
    optionD: 'Деревня вдали от всех',
    image: '/images/questions/q004.jpg',
  },
  {
    emoji: '🚐',
    category: 'Путешествия',
    question: 'Год в путешествиях — как?',
    optionA: 'В фургоне, новая страна каждую неделю',
    optionB: 'Месяц в одном городе, потом дальше',
    optionC: 'Полгода в одной стране, потом смена',
    optionD: 'Зимовка на одном острове весь год',
    image: '/images/questions/q005.jpg',
  },
  {
    emoji: '🛂',
    category: 'Путешествия',
    question: 'Лучше один отпуск...',
    optionA: 'Один большой, на месяц',
    optionB: 'Длинный на 3 недели',
    optionC: 'Два по 10 дней',
    optionD: 'Много коротких уикендов',
    image: '/images/questions/q006.jpg',
  },
  {
    emoji: '🧳',
    category: 'Путешествия',
    question: 'Чемодан для путешествия:',
    optionA: 'Только ручная кладь, всё налегке',
    optionB: 'Небольшой чемодан, всё нужное',
    optionC: 'Большой чемодан на всякий случай',
    optionD: 'Два чемодана и сумка сверху',
    image: '/images/questions/q007.jpg',
  },
  {
    emoji: '🗾',
    category: 'Путешествия',
    question: 'Куда хочется уехать впервые?',
    optionA: 'В Японию — совсем другая культура',
    optionB: 'В Южную Корею — необычно и современно',
    optionC: 'В Италию — еда и история',
    optionD: 'В Грецию — море и расслабленность',
    image: '/images/questions/q008.jpg',
  },
  {
    emoji: '🚆',
    category: 'Путешествия',
    question: 'На чём приятнее путешествовать?',
    optionA: 'Своим авто — полная свобода',
    optionB: 'Поездом — пейзажи и комфорт',
    optionC: 'Автобусом — дешевле и душевнее',
    optionD: 'Самолётом — быстрее на месте',
    image: '/images/questions/q009.jpg',
  },

  // --- 2. Еда и кухня ---
  {
    emoji: '🍕',
    category: 'Еда и кухня',
    question: 'Вечер пятницы — что заказываем?',
    optionA: 'Готовлю ужин сам с нуля',
    optionB: 'Заказываем доставку домой',
    optionC: 'Идём в любимое кафе',
    optionD: 'Ужин в красивом ресторане',
    image: '/images/questions/q010.jpg',
  },
  {
    emoji: '🌶️',
    category: 'Еда и кухня',
    question: 'Острая еда — это...',
    optionA: 'Чем острее, тем вкуснее — обожаю',
    optionB: 'Люблю средне-острое',
    optionC: 'Чуть-чуть ок, но без фанатизма',
    optionD: 'Совсем не переношу остроту',
    image: '/images/questions/q011.jpg',
  },
  {
    emoji: '🍳',
    category: 'Еда и кухня',
    question: 'Как я отношусь к готовке дома?',
    optionA: 'Обожаю готовить, это хобби',
    optionB: 'Готовлю с удовольствием, без сложного',
    optionC: 'Готовлю редко, базовые блюда',
    optionD: 'Лучше доставка или кафе',
    image: '/images/questions/q012.jpg',
  },
  {
    emoji: '🥗',
    category: 'Еда и кухня',
    question: 'Моё отношение к овощам:',
    optionA: 'Половина тарелки — салат всегда',
    optionB: 'Овощи люблю и часто ем',
    optionC: 'Ем только как гарнир к мясу',
    optionD: 'Овощи — это не еда',
    image: '/images/questions/q013.jpg',
  },
  {
    emoji: '☕',
    category: 'Еда и кухня',
    question: 'Утренний напиток жизни:',
    optionA: 'Крепкий эспрессо без сахара',
    optionB: 'Капучино или латте',
    optionC: 'Чёрный или зелёный чай',
    optionD: 'Просто вода или сок',
    image: '/images/questions/q014.jpg',
  },
  {
    emoji: '🍰',
    category: 'Еда и кухня',
    question: 'Десерт — это...',
    optionA: 'Святое, после каждого ужина',
    optionB: 'Часто балую себя сладким',
    optionC: 'Только по особым поводам',
    optionD: 'Не ем сладкое почти никогда',
    image: '/images/questions/q015.jpg',
  },
  {
    emoji: '🍣',
    category: 'Еда и кухня',
    question: 'Любимая кухня мира:',
    optionA: 'Азиатская — суши, рамен, том ям',
    optionB: 'Средиземноморская — паста, морепродукты',
    optionC: 'Своя национальная — родное и привычное',
    optionD: 'Мясная — стейки, бургеры, гриль',
    image: '/images/questions/q016.jpg',
  },
  {
    emoji: '🍔',
    category: 'Еда и кухня',
    question: 'Фастфуд в моей жизни:',
    optionA: 'Регулярно, это вкусно и удобно',
    optionB: 'Иногда можно себя побаловать',
    optionC: 'Очень редко, по случаю',
    optionD: 'Не ем уже давно, противно',
    image: '/images/questions/q017.jpg',
  },
  {
    emoji: '🥩',
    category: 'Еда и кухня',
    question: 'Мог бы стать вегетарианцем?',
    optionA: 'Уже почти веган, мясо не нужно',
    optionB: 'Легко, мясо ем редко',
    optionC: 'Сложно, но смог бы попробовать',
    optionD: 'Без мяса жизнь не та',
    image: '/images/questions/q018.jpg',
  },
  {
    emoji: '🍷',
    category: 'Еда и кухня',
    question: 'Вечером бокал чего?',
    optionA: 'Сухое красное вино',
    optionB: 'Игристое или белое вино',
    optionC: 'Холодное пиво или сидр',
    optionD: 'Чай или вода, без алкоголя',
    image: '/images/questions/q019.jpg',
  },

  // --- 3. Утро и вечер ---
  {
    emoji: '🌅',
    category: 'Утро и вечер',
    question: 'Кто я по биоритмам?',
    optionA: 'Жаворонок — встаю в 5-6 утра',
    optionB: 'Ранняя пташка — встаю до 8',
    optionC: 'Вечерний тип — оживаю после обеда',
    optionD: 'Сова — самый продуктивный к ночи',
    image: '/images/questions/q020.jpg',
  },
  {
    emoji: '⏰',
    category: 'Утро и вечер',
    question: 'Будильник звонит — что я делаю?',
    optionA: 'Просыпаюсь до будильника сам',
    optionB: 'Встаю сразу, без отложений',
    optionC: 'Один раз отложу и встаю',
    optionD: 'Откладываю 5 раз минимум',
    image: '/images/questions/q021.jpg',
  },
  {
    emoji: '🛏️',
    category: 'Утро и вечер',
    question: 'Идеальное утро начинается с...',
    optionA: 'Полной тишины и медитации',
    optionB: 'Кофе в одиночестве',
    optionC: 'Спокойного разговора за завтраком',
    optionD: 'Бодрой музыки и активности',
    image: '/images/questions/q022.jpg',
  },
  {
    emoji: '🌙',
    category: 'Утро и вечер',
    question: 'Перед сном я обычно...',
    optionA: 'Читаю бумажную книгу',
    optionB: 'Смотрю фильм или сериал',
    optionC: 'Слушаю музыку или подкаст',
    optionD: 'Скроллю телефон до отключки',
    image: '/images/questions/q023.jpg',
  },
  {
    emoji: '🚿',
    category: 'Утро и вечер',
    question: 'Душ я принимаю...',
    optionA: 'Только утром, чтобы проснуться',
    optionB: 'Утром и иногда вечером',
    optionC: 'Чаще вечером, для расслабления',
    optionD: 'Только вечером, обязательно',
    image: '/images/questions/q024.jpg',
  },
  {
    emoji: '🍳',
    category: 'Утро и вечер',
    question: 'Завтрак для меня — это...',
    optionA: 'Святое, плотный и обязательный',
    optionB: 'Обязательно, но что-то лёгкое',
    optionC: 'Иногда пропускаю, не критично',
    optionD: 'Никогда не ем по утрам',
    image: '/images/questions/q025.jpg',
  },
  {
    emoji: '😴',
    category: 'Утро и вечер',
    question: 'Сколько часов сна мне нужно?',
    optionA: '5-6 часов и я бодр',
    optionB: '7 часов — оптимально',
    optionC: '8 часов, иначе тяжело',
    optionD: '9-10 часов, я соня',
    image: '/images/questions/q026.jpg',
  },
  {
    emoji: '🌃',
    category: 'Утро и вечер',
    question: 'Лучшее время суток:',
    optionA: 'Рассвет — мир ещё спит',
    optionB: 'Утро — энергия и кофе',
    optionC: 'Вечер — все дела сделаны',
    optionD: 'Глубокая ночь — тишина и я',
    image: '/images/questions/q027.jpg',
  },
  {
    emoji: '🛋️',
    category: 'Утро и вечер',
    question: 'Выходное утро провожу...',
    optionA: 'Сплю до полудня под одеялом',
    optionB: 'Долгий завтрак и кофе в кровати',
    optionC: 'Встаю в обычное время и читаю',
    optionD: 'На пробежке или зарядке в 7',
    image: '/images/questions/q028.jpg',
  },
  {
    emoji: '🕯️',
    category: 'Утро и вечер',
    question: 'Вечерний ритуал — это...',
    optionA: 'Ванна, свечи, полная тишина',
    optionB: 'Книга и травяной чай',
    optionC: 'Сериал с пледом и попкорном',
    optionD: 'Активные игры или прогулка',
    image: '/images/questions/q029.jpg',
  },

  // --- 4. Деньги и финансы ---
  {
    emoji: '💰',
    category: 'Деньги и финансы',
    question: 'Получил премию — что делаю?',
    optionA: 'Всё откладываю на будущее',
    optionB: 'Большую часть откладываю',
    optionC: 'Делю пополам: трачу и копию',
    optionD: 'Сразу трачу на приятное',
    image: '/images/questions/q030.jpg',
  },
  {
    emoji: '📊',
    category: 'Деньги и финансы',
    question: 'Бюджет я веду:',
    optionA: 'Каждый рубль учтён в приложении',
    optionB: 'Слежу за крупными тратами',
    optionC: 'На глаз, главное не в минус',
    optionD: 'Не считаю вообще',
    image: '/images/questions/q031.jpg',
  },
  {
    emoji: '🏦',
    category: 'Деньги и финансы',
    question: 'Подушка безопасности:',
    optionA: 'На год жизни минимум',
    optionB: 'На 6 месяцев точно есть',
    optionC: 'На пару месяцев, и то с натяжкой',
    optionD: 'А что это такое?',
    image: '/images/questions/q032.jpg',
  },
  {
    emoji: '💎',
    category: 'Деньги и финансы',
    question: 'Дорогая покупка — мой принцип:',
    optionA: 'Только премиум, лучшее из лучшего',
    optionB: 'Лучше реже, но качественнее',
    optionC: 'Среднее по цене и качеству',
    optionD: 'Дёшево и часто меняю',
    image: '/images/questions/q033.jpg',
  },
  {
    emoji: '🎁',
    category: 'Деньги и финансы',
    question: 'Подарки я люблю...',
    optionA: 'Только дарить — это моё счастье',
    optionB: 'Дарить больше, чем получать',
    optionC: 'И дарить, и получать одинаково',
    optionD: 'Получать — это самое приятное',
    image: '/images/questions/q034.jpg',
  },
  {
    emoji: '🏠',
    category: 'Деньги и финансы',
    question: 'Большая мечта на деньги:',
    optionA: 'Свой большой дом с участком',
    optionB: 'Уютная квартира в любимом городе',
    optionC: 'Жить в путешествиях по миру',
    optionD: 'Финансовая свобода и ранняя пенсия',
    image: '/images/questions/q035.jpg',
  },
  {
    emoji: '📈',
    category: 'Деньги и финансы',
    question: 'Инвестиции — это...',
    optionA: 'Профессионально вкладываю и торгую',
    optionB: 'Изучаю и потихоньку инвестирую',
    optionC: 'Слишком сложно, держу в банке',
    optionD: 'Лучше под подушкой, надёжнее',
    image: '/images/questions/q036.jpg',
  },
  {
    emoji: '🛍️',
    category: 'Деньги и финансы',
    question: 'Шопинг для меня:',
    optionA: 'Любимое хобби, терапия',
    optionB: 'Приятное занятие время от времени',
    optionC: 'Только по необходимости',
    optionD: 'Стресс, избегаю как могу',
    image: '/images/questions/q037.jpg',
  },
  {
    emoji: '💳',
    category: 'Деньги и финансы',
    question: 'Кредиты — моё мнение:',
    optionA: 'Беру охотно, если выгодно',
    optionB: 'Только на крупное — ипотека, авто',
    optionC: 'Стараюсь обходиться без них',
    optionD: 'Только наличные, никаких долгов',
    image: '/images/questions/q038.jpg',
  },
  {
    emoji: '🤝',
    category: 'Деньги и финансы',
    question: 'Семейный бюджет лучше...',
    optionA: 'Полностью общий, всё в одной кассе',
    optionB: 'Общий, но с личными карманами',
    optionC: 'Раздельный, скидываемся на общее',
    optionD: 'Полностью раздельный, каждый сам',
    image: '/images/questions/q039.jpg',
  },

  // --- 5. Карьера и амбиции ---
  {
    emoji: '💼',
    category: 'Карьера и амбиции',
    question: 'Работа в моей жизни:',
    optionA: 'Призвание, смысл и страсть',
    optionB: 'Любимое дело, хорошо платят',
    optionC: 'Нормальная работа, не люблю не ненавижу',
    optionD: 'Только способ заработать',
    image: '/images/questions/q040.jpg',
  },
  {
    emoji: '🚀',
    category: 'Карьера и амбиции',
    question: 'Где вижу себя через 5 лет?',
    optionA: 'Свой успешный бизнес',
    optionB: 'Фриланс с большими клиентами',
    optionC: 'Топ-должность в крутой компании',
    optionD: 'Там же, мне и так хорошо',
    image: '/images/questions/q041.jpg',
  },
  {
    emoji: '🏖️',
    category: 'Карьера и амбиции',
    question: 'Идеальный баланс работы и жизни:',
    optionA: '2-3 дня в неделю работаю',
    optionB: 'Стандартные 8 часов, и хватит',
    optionC: 'Работа важна, но семья важнее',
    optionD: 'Работа — это жизнь, мне нравится',
    image: '/images/questions/q042.jpg',
  },
  {
    emoji: '🏡',
    category: 'Карьера и амбиции',
    question: 'Где мне лучше работается?',
    optionA: 'Из дома в пижаме каждый день',
    optionB: 'В кафе или коворкинге',
    optionC: 'Гибрид: дом и офис пополам',
    optionD: 'В офисе среди коллег',
    image: '/images/questions/q043.jpg',
  },
  {
    emoji: '🎓',
    category: 'Карьера и амбиции',
    question: 'Учиться новому я люблю?',
    optionA: 'Постоянно — курсы, книги, лекции',
    optionB: 'Регулярно — по своей теме',
    optionC: 'Иногда, когда надо для работы',
    optionD: 'Достаточно того, что знаю',
    image: '/images/questions/q044.jpg',
  },
  {
    emoji: '🤐',
    category: 'Карьера и амбиции',
    question: 'Уволиться без плана Б — смог бы?',
    optionA: 'Уже делал, без раздумий',
    optionB: 'Да, если совсем плохо',
    optionC: 'Только когда есть финансовая подушка',
    optionD: 'Никогда, сначала найду новое',
    image: '/images/questions/q045.jpg',
  },
  {
    emoji: '👔',
    category: 'Карьера и амбиции',
    question: 'Мой стиль работы:',
    optionA: 'Лидер, веду команду за собой',
    optionB: 'Координатор, организую процесс',
    optionC: 'Эксперт, делаю свою часть',
    optionD: 'Одиночка, работаю сам',
    image: '/images/questions/q046.jpg',
  },
  {
    emoji: '🧠',
    category: 'Карьера и амбиции',
    question: 'Что важнее в работе?',
    optionA: 'Высокая зарплата прежде всего',
    optionB: 'Деньги и интерес одинаково',
    optionC: 'Интересные задачи и команда',
    optionD: 'Смысл и польза, деньги не главное',
    image: '/images/questions/q047.jpg',
  },
  {
    emoji: '✏️',
    category: 'Карьера и амбиции',
    question: 'Профессия мечты — это та, где...',
    optionA: 'Полная творческая свобода',
    optionB: 'Творчество с понятной структурой',
    optionC: 'Стабильность с интересными задачами',
    optionD: 'Чёткая стабильность и предсказуемость',
    image: '/images/questions/q048.jpg',
  },
  {
    emoji: '📅',
    category: 'Карьера и амбиции',
    question: 'Отпуск я беру:',
    optionA: 'Все дни до последнего, обязательно',
    optionB: 'Почти все, иногда переношу',
    optionC: 'Половину дней, остальное в работу',
    optionD: 'Минимум, работа важнее',
    image: '/images/questions/q049.jpg',
  },

  // --- 6. Дом и уют ---
  {
    emoji: '🏠',
    category: 'Дом и уют',
    question: 'Идеальное жильё мечты:',
    optionA: 'Свой дом с садом за городом',
    optionB: 'Таунхаус в пригороде',
    optionC: 'Большая квартира в спальном районе',
    optionD: 'Студия в самом центре города',
    image: '/images/questions/q050.jpg',
  },
  {
    emoji: '🧹',
    category: 'Дом и уют',
    question: 'Дома у меня обычно:',
    optionA: 'Идеальный порядок, всё блестит',
    optionB: 'Чисто и аккуратно',
    optionC: 'Творческий беспорядок',
    optionD: 'Хаос, и меня это устраивает',
    image: '/images/questions/q051.jpg',
  },
  {
    emoji: '🛋️',
    category: 'Дом и уют',
    question: 'Мой стиль интерьера:',
    optionA: 'Строгий минимализм, ничего лишнего',
    optionB: 'Скандинавский — светло и просто',
    optionC: 'Уютно с деталями и текстилем',
    optionD: 'Максимализм — много декора и красок',
    image: '/images/questions/q052.jpg',
  },
  {
    emoji: '🪴',
    category: 'Дом и уют',
    question: 'Растения дома:',
    optionA: 'Джунгли на каждом подоконнике',
    optionB: 'Десяток зелёных любимцев',
    optionC: 'Пара неприхотливых растений',
    optionD: 'Растений нет вообще',
    image: '/images/questions/q053.jpg',
  },
  {
    emoji: '🐕',
    category: 'Дом и уют',
    question: 'Питомец дома:',
    optionA: 'Обязательно нужен, мечтаю',
    optionB: 'Хотел бы, если будет время',
    optionC: 'Можно, но не обязательно',
    optionD: 'Без животных свободнее',
    image: '/images/questions/q054.jpg',
  },
  {
    emoji: '🧺',
    category: 'Дом и уют',
    question: 'Уборка дома — это:',
    optionA: 'Расписание, каждый день понемногу',
    optionB: 'Один раз в неделю генералка',
    optionC: 'Раз в две недели, по настроению',
    optionD: 'Когда уже совсем невозможно',
    image: '/images/questions/q055.jpg',
  },
  {
    emoji: '🍽️',
    category: 'Дом и уют',
    question: 'Едим дома мы:',
    optionA: 'Только за столом, с тарелками и приборами',
    optionB: 'Обычно за столом, иногда у тв',
    optionC: 'Чаще на диване перед экраном',
    optionD: 'Где придётся, прямо из коробки',
    image: '/images/questions/q056.jpg',
  },
  {
    emoji: '🔔',
    category: 'Дом и уют',
    question: 'Гости в доме:',
    optionA: 'Чем чаще, тем лучше — двери открыты',
    optionB: 'Часто, заранее приглашаю',
    optionC: 'Иногда, только близких',
    optionD: 'Очень редко, мой дом — моя крепость',
    image: '/images/questions/q057.jpg',
  },
  {
    emoji: '🌡️',
    category: 'Дом и уют',
    question: 'Температура в комнате:',
    optionA: 'Холодно, окно открыто всегда',
    optionB: 'Прохладно, около 19 градусов',
    optionC: 'Комфортно, 22-23 градуса',
    optionD: 'Жара и плед, греюсь как могу',
    image: '/images/questions/q058.jpg',
  },
  {
    emoji: '🛏️',
    category: 'Дом и уют',
    question: 'Кровать утром:',
    optionA: 'Всегда заправлена идеально',
    optionB: 'Заправляю почти каждый день',
    optionC: 'Иногда заправляю, по настроению',
    optionD: 'Зачем, всё равно лягу вечером',
    image: '/images/questions/q059.jpg',
  },

  // --- 7. Друзья и общение ---
  {
    emoji: '🥂',
    category: 'Друзья и общение',
    question: 'Пятница вечером:',
    optionA: 'Большая шумная компания в баре',
    optionB: 'Ужин с группой друзей',
    optionC: 'Тихий вечер с одним близким',
    optionD: 'Один дома, наконец-то тишина',
    image: '/images/questions/q060.jpg',
  },
  {
    emoji: '🤐',
    category: 'Друзья и общение',
    question: 'Я по натуре:',
    optionA: 'Яркий экстраверт, без людей умираю',
    optionB: 'Скорее общительный, люблю людей',
    optionC: 'Скорее интроверт, нужно своё время',
    optionD: 'Глубокий интроверт, люди утомляют',
    image: '/images/questions/q061.jpg',
  },
  {
    emoji: '📱',
    category: 'Друзья и общение',
    question: 'Звонок от друга в субботу:',
    optionA: 'Беру с восторгом, рад любому',
    optionB: 'Отвечаю и долго болтаю',
    optionC: 'Беру, но коротко',
    optionD: 'Лучше напишу позже',
    image: '/images/questions/q062.jpg',
  },
  {
    emoji: '👫',
    category: 'Друзья и общение',
    question: 'Друзей у меня:',
    optionA: 'Очень много и самых разных',
    optionB: 'Большой круг общения',
    optionC: 'Небольшая компания близких',
    optionD: 'Один-два самых верных',
    image: '/images/questions/q063.jpg',
  },
  {
    emoji: '🎂',
    category: 'Друзья и общение',
    question: 'Свой день рождения отмечаю:',
    optionA: 'Большая вечеринка, все приглашены',
    optionB: 'Дома с компанией друзей',
    optionC: 'Тихий ужин с самыми близкими',
    optionD: 'В одиночестве, не люблю шум',
    image: '/images/questions/q064.jpg',
  },
  {
    emoji: '💬',
    category: 'Друзья и общение',
    question: 'Чтобы что-то обсудить, я:',
    optionA: 'Звоню и могу говорить часами',
    optionB: 'Звоню коротко по делу',
    optionC: 'Пишу — так удобнее',
    optionD: 'Лучше встретимся лично',
    image: '/images/questions/q065.jpg',
  },
  {
    emoji: '🎉',
    category: 'Друзья и общение',
    question: 'Корпоративы и тусовки:',
    optionA: 'Душа компании, остаюсь до утра',
    optionB: 'Иду с удовольствием, ухожу вовремя',
    optionC: 'Прихожу из вежливости, ухожу первым',
    optionD: 'Стараюсь не ходить совсем',
    image: '/images/questions/q066.jpg',
  },
  {
    emoji: '🤝',
    category: 'Друзья и общение',
    question: 'Новые знакомства:',
    optionA: 'Заговорю с любым в очереди',
    optionB: 'Легко знакомлюсь в нужной ситуации',
    optionC: 'С трудом, нужно время освоиться',
    optionD: 'Избегаю как могу, новые люди — стресс',
    image: '/images/questions/q067.jpg',
  },
  {
    emoji: '🍻',
    category: 'Друзья и общение',
    question: 'Лучший момент с друзьями:',
    optionA: 'Шумная вечеринка с танцами',
    optionB: 'Совместное путешествие',
    optionC: 'Долгий ужин в ресторане',
    optionD: 'Разговоры по душам на кухне',
    image: '/images/questions/q068.jpg',
  },
  {
    emoji: '🚪',
    category: 'Друзья и общение',
    question: 'Друг приехал без предупреждения:',
    optionA: 'Супер! Заходи, давно не виделись!',
    optionB: 'Рад, но мог бы и предупредить',
    optionC: 'Неудобно, но впущу',
    optionD: 'Лучше бы написал заранее',
    image: '/images/questions/q069.jpg',
  },

  // --- 8. Романтика ---
  {
    emoji: '💌',
    category: 'Романтика',
    question: 'Как я выражаю чувства?',
    optionA: 'Словами — говорю всё прямо и часто',
    optionB: 'Прикосновениями — обнимаю, держу за руку',
    optionC: 'Подарками и приятными сюрпризами',
    optionD: 'Делами и заботой — это моё всё',
    image: '/images/questions/q070.jpg',
  },
  {
    emoji: '🌹',
    category: 'Романтика',
    question: 'Идеальное свидание для меня:',
    optionA: 'Романтический ужин при свечах',
    optionB: 'Прогулка по красивому месту',
    optionC: 'Совместный мастер-класс или активность',
    optionD: 'Экстрим — каток, квест, поход',
    image: '/images/questions/q071.jpg',
  },
  {
    emoji: '🎁',
    category: 'Романтика',
    question: 'Я предпочитаю получать в подарок:',
    optionA: 'Дорогую материальную вещь',
    optionB: 'Маленький, но продуманный сувенир',
    optionC: 'Совместный опыт — поездку, ужин',
    optionD: 'Эмоции — концерт, спа, приключение',
    image: '/images/questions/q072.jpg',
  },
  {
    emoji: '🤗',
    category: 'Романтика',
    question: 'Объятия в течение дня:',
    optionA: 'Постоянно, чем больше тем лучше',
    optionB: 'Часто, мне это важно',
    optionC: 'По настроению, не часто',
    optionD: 'Редко, мне хватает личного пространства',
    image: '/images/questions/q073.jpg',
  },
  {
    emoji: '💋',
    category: 'Романтика',
    question: 'Признания в любви:',
    optionA: 'Говорю по несколько раз в день',
    optionB: 'Каждый день обязательно',
    optionC: 'Время от времени, по моменту',
    optionD: 'Только по особым случаям',
    image: '/images/questions/q074.jpg',
  },
  {
    emoji: '🎶',
    category: 'Романтика',
    question: 'Песня "о нас" — это...',
    optionA: 'Медленная романтическая баллада',
    optionB: 'Лирическая, но не слишком грустная',
    optionC: 'Что-то весёлое и танцевальное',
    optionD: 'Энергичный гимн на стадионе',
    image: '/images/questions/q075.jpg',
  },
  {
    emoji: '🕯️',
    category: 'Романтика',
    question: 'Романтичный вечер дома:',
    optionA: 'Свечи, ванна, массаж и тишина',
    optionB: 'Ужин с вином и музыкой',
    optionC: 'Кино под пледом с попкорном',
    optionD: 'Настолки и смех весь вечер',
    image: '/images/questions/q076.jpg',
  },
  {
    emoji: '✉️',
    category: 'Романтика',
    question: 'В разлуке я предпочитаю:',
    optionA: 'Видеозвонки часами каждый день',
    optionB: 'Голосовые сообщения постоянно',
    optionC: 'Тёплая переписка в течение дня',
    optionD: 'Короткие сообщения по делу',
    image: '/images/questions/q077.jpg',
  },
  {
    emoji: '📸',
    category: 'Романтика',
    question: 'Совместные фото в соцсетях:',
    optionA: 'Регулярно — я горжусь и хвастаюсь',
    optionB: 'По особым датам — праздники, поездки',
    optionC: 'Очень редко, личное не для всех',
    optionD: 'Никогда, моя жизнь не для интернета',
    image: '/images/questions/q078.jpg',
  },
  {
    emoji: '👰',
    category: 'Романтика',
    question: 'Свадьба должна быть:',
    optionA: 'Огромная и пышная, как в кино',
    optionB: 'Большая с друзьями и роднёй',
    optionC: 'Камерная, только самые близкие',
    optionD: 'Только двое, всё остальное лишнее',
    image: '/images/questions/q079.jpg',
  },

  // --- 9. Развлечения ---
  {
    emoji: '🎮',
    category: 'Развлечения',
    question: 'Свободный вечер — это...',
    optionA: 'Видеоигры на консоли часами',
    optionB: 'Настольные игры с друзьями',
    optionC: 'Книга и тёплый плед',
    optionD: 'Прогулка или активность на воздухе',
    image: '/images/questions/q080.jpg',
  },
  {
    emoji: '📚',
    category: 'Развлечения',
    question: 'Книги я читаю:',
    optionA: 'Несколько в месяц, не могу без них',
    optionB: 'Одну в месяц, регулярно',
    optionC: 'Несколько в год, по настроению',
    optionD: 'Почти не читаю, мне скучно',
    image: '/images/questions/q081.jpg',
  },
  {
    emoji: '🎨',
    category: 'Развлечения',
    question: 'Моё хобби должно быть...',
    optionA: 'Глубоко творческим — рисую, пишу, создаю',
    optionB: 'Спокойным — рукоделие, готовка',
    optionC: 'Социальным — клубы, кружки',
    optionD: 'Активным — спорт, танцы, движение',
    image: '/images/questions/q082.jpg',
  },
  {
    emoji: '🎤',
    category: 'Развлечения',
    question: 'Караоке в баре:',
    optionA: 'Первый беру микрофон, пою всё',
    optionB: 'Пою, если попросят, с удовольствием',
    optionC: 'Только в большой компании за компанию',
    optionD: 'Никогда, лучше уйду',
    image: '/images/questions/q083.jpg',
  },
  {
    emoji: '🎬',
    category: 'Развлечения',
    question: 'Фильм смотрю:',
    optionA: 'Только в кино, на огромном экране',
    optionB: 'В кино с особыми фильмами',
    optionC: 'Дома на проекторе или большом тв',
    optionD: 'На ноуте под одеялом',
    image: '/images/questions/q084.jpg',
  },
  {
    emoji: '🧩',
    category: 'Развлечения',
    question: 'Дождливый день — что делаю?',
    optionA: 'Книга, чай, плед и абсолютная тишина',
    optionB: 'Пазл или творчество дома',
    optionC: 'Фильм или сериал марафон',
    optionD: 'Иду в торговый центр или кафе',
    image: '/images/questions/q085.jpg',
  },
  {
    emoji: '🎲',
    category: 'Развлечения',
    question: 'Настольные игры:',
    optionA: 'Сложные стратегии на много часов',
    optionB: 'Серьёзные, но не марафонские',
    optionC: 'Лёгкие семейные на час',
    optionD: 'Быстрые весёлые на 15 минут',
    image: '/images/questions/q086.jpg',
  },
  {
    emoji: '🃏',
    category: 'Развлечения',
    question: 'Азартные игры:',
    optionA: 'Обожаю казино и адреналин',
    optionB: 'Иногда играю на мелкие ставки',
    optionC: 'Редко и без денег',
    optionD: 'Никогда, это пустая трата',
    image: '/images/questions/q087.jpg',
  },
  {
    emoji: '🎢',
    category: 'Развлечения',
    question: 'Парк аттракционов:',
    optionA: 'Все экстремальные горки подряд',
    optionB: 'Большинство горок, кроме самых страшных',
    optionC: 'Спокойные аттракционы и поесть',
    optionD: 'Только колесо обозрения и фотки',
    image: '/images/questions/q088.jpg',
  },
  {
    emoji: '🪩',
    category: 'Развлечения',
    question: 'Танцпол в клубе:',
    optionA: 'Танцую до утра без остановки',
    optionB: 'Танцую часть вечера',
    optionC: 'Иногда выхожу на пару песен',
    optionD: 'Стою у бара или ухожу',
    image: '/images/questions/q089.jpg',
  },

  // --- 10. Спорт и здоровье ---
  {
    emoji: '🏃',
    category: 'Спорт и здоровье',
    question: 'Спорт в моей жизни:',
    optionA: 'Каждый день, без него никак',
    optionB: '3-4 раза в неделю регулярно',
    optionC: 'Пару раз в неделю по настроению',
    optionD: 'Хожу-дышу — уже спорт',
    image: '/images/questions/q090.jpg',
  },
  {
    emoji: '🏋️',
    category: 'Спорт и здоровье',
    question: 'Идеальная тренировка:',
    optionA: 'Тяжёлые веса, до отказа',
    optionB: 'Силовая средней интенсивности',
    optionC: 'Кардио и функциональная',
    optionD: 'Йога, растяжка, дыхание',
    image: '/images/questions/q091.jpg',
  },
  {
    emoji: '🥗',
    category: 'Спорт и здоровье',
    question: 'Здоровое питание для меня:',
    optionA: 'Считаю калории, БЖУ, всё взвешено',
    optionB: 'Слежу за питанием без подсчётов',
    optionC: 'Стараюсь, но без фанатизма',
    optionD: 'Ем что хочу, главное вкусно',
    image: '/images/questions/q092.jpg',
  },
  {
    emoji: '🚴',
    category: 'Спорт и здоровье',
    question: 'Активность по выходным:',
    optionA: 'Длинный поход или вело-марафон',
    optionB: 'Прогулка, ролики, велосипед пару часов',
    optionC: 'Короткая прогулка для галочки',
    optionD: 'Диван, плед, никуда не пойду',
    image: '/images/questions/q093.jpg',
  },
  {
    emoji: '💊',
    category: 'Спорт и здоровье',
    question: 'Заболел — мой алгоритм:',
    optionA: 'Сразу к врачу при любых симптомах',
    optionB: 'К врачу, если за пару дней не прошло',
    optionC: 'Лечусь сам проверенными средствами',
    optionD: 'Чай с мёдом и переждать',
    image: '/images/questions/q094.jpg',
  },
  {
    emoji: '🥛',
    category: 'Спорт и здоровье',
    question: 'Сколько воды пью в день?',
    optionA: '3 литра, всё чётко по часам',
    optionB: '2 литра, контролирую',
    optionC: 'Когда вспомню, около литра',
    optionD: 'Почти не пью воду, кофе и чай',
    image: '/images/questions/q095.jpg',
  },
  {
    emoji: '🏊',
    category: 'Спорт и здоровье',
    question: 'Лучший вид активности:',
    optionA: 'Командный спорт с азартом',
    optionB: 'Парная активность — теннис, бадминтон',
    optionC: 'Индивидуальный — бег, плавание',
    optionD: 'Йога или медитация в одиночестве',
    image: '/images/questions/q096.jpg',
  },
  {
    emoji: '🧘',
    category: 'Спорт и здоровье',
    question: 'Медитация и осознанность:',
    optionA: 'Практикую каждый день, образ жизни',
    optionB: 'Практикую регулярно',
    optionC: 'Пробую иногда, не зашло',
    optionD: 'Не моё, скучно сидеть',
    image: '/images/questions/q097.jpg',
  },
  {
    emoji: '🚭',
    category: 'Спорт и здоровье',
    question: 'Вредные привычки:',
    optionA: 'Полный ЗОЖ, ничего вредного',
    optionB: 'Веду здоровый образ, но не строго',
    optionC: 'Есть привычки, но не страдаю',
    optionD: 'Жизнь одна, ни в чём не отказываю',
    image: '/images/questions/q098.jpg',
  },
  {
    emoji: '☀️',
    category: 'Спорт и здоровье',
    question: 'Защита от солнца:',
    optionA: 'SPF каждый день, даже зимой',
    optionB: 'SPF летом и в солнечные дни',
    optionC: 'Только на пляже и в горах',
    optionD: 'Никогда, не вижу смысла',
    image: '/images/questions/q099.jpg',
  },

  // --- 11. Технологии ---
  {
    emoji: '📱',
    category: 'Технологии',
    question: 'Сколько часов в день в телефоне?',
    optionA: 'Меньше часа, контролирую жёстко',
    optionB: '1-2 часа, в основном по делу',
    optionC: '3-5 часов, бывает залипаю',
    optionD: 'Больше 6, и не считаю',
    image: '/images/questions/q100.jpg',
  },
  {
    emoji: '🔔',
    category: 'Технологии',
    question: 'Уведомления на телефоне:',
    optionA: 'Все включены — нужно быть в курсе',
    optionB: 'Включены избранные приложения',
    optionC: 'Только звонки и сообщения',
    optionD: 'Всё выключено, тишина',
    image: '/images/questions/q101.jpg',
  },
  {
    emoji: '📸',
    category: 'Технологии',
    question: 'Соцсети для меня:',
    optionA: 'Активно постю каждый день',
    optionB: 'Иногда что-то выкладываю',
    optionC: 'Только читаю, ничего не выкладываю',
    optionD: 'Удалил все, не пользуюсь',
    image: '/images/questions/q102.jpg',
  },
  {
    emoji: '🤖',
    category: 'Технологии',
    question: 'Искусственный интеллект:',
    optionA: 'Использую везде, это будущее',
    optionB: 'Часто пользуюсь, удобно',
    optionC: 'Иногда, для конкретных задач',
    optionD: 'Не доверяю, сам разберусь',
    image: '/images/questions/q103.jpg',
  },
  {
    emoji: '⌚',
    category: 'Технологии',
    question: 'Умные часы на руке:',
    optionA: 'Обязательно, отслеживаю всё',
    optionB: 'Ношу для удобства',
    optionC: 'Обычные стильные часы',
    optionD: 'Без часов вообще',
    image: '/images/questions/q104.jpg',
  },
  {
    emoji: '🎧',
    category: 'Технологии',
    question: 'Наушники в общественных местах:',
    optionA: 'Всегда — это моя крепость',
    optionB: 'Часто, особенно в транспорте',
    optionC: 'Только когда хочу музыку',
    optionD: 'Почти не пользуюсь',
    image: '/images/questions/q105.jpg',
  },
  {
    emoji: '💻',
    category: 'Технологии',
    question: 'Apple или Android?',
    optionA: 'Фанат Apple, вся экосистема',
    optionB: 'iPhone, но без фанатизма',
    optionC: 'Android — больше свободы',
    optionD: 'Что подешевле, всё равно',
    image: '/images/questions/q106.jpg',
  },
  {
    emoji: '📺',
    category: 'Технологии',
    question: 'Гаджет, без которого жизни нет:',
    optionA: 'Только смартфон, всё в нём',
    optionB: 'Смартфон и наушники',
    optionC: 'Ноутбук — рабочий инструмент',
    optionD: 'Могу обойтись без всего на неделю',
    image: '/images/questions/q107.jpg',
  },
  {
    emoji: '📵',
    category: 'Технологии',
    question: 'Цифровой детокс — смог бы?',
    optionA: 'Месяц без интернета — давно мечтаю',
    optionB: 'Неделю спокойно, без проблем',
    optionC: 'Пару дней смогу',
    optionD: 'Полдня без телефона — паника',
    image: '/images/questions/q108.jpg',
  },
  {
    emoji: '🎮',
    category: 'Технологии',
    question: 'Телефон во время еды:',
    optionA: 'Никогда, всегда убираю',
    optionB: 'За столом стараюсь не доставать',
    optionC: 'Иногда проверяю, не страшно',
    optionD: 'Всегда листаю, это нормально',
    image: '/images/questions/q109.jpg',
  },

  // --- 12. Природа ---
  {
    emoji: '🌲',
    category: 'Природа',
    question: 'Лес или море?',
    optionA: 'Глубокий хвойный лес — тишина',
    optionB: 'Смешанный лес у озера',
    optionC: 'Море с уютным пляжем',
    optionD: 'Океан с большими волнами',
    image: '/images/questions/q110.jpg',
  },
  {
    emoji: '🍂',
    category: 'Природа',
    question: 'Любимое время года:',
    optionA: 'Снежная морозная зима',
    optionB: 'Цветущая ароматная весна',
    optionC: 'Жаркое яркое лето',
    optionD: 'Золотая дождливая осень',
    image: '/images/questions/q111.jpg',
  },
  {
    emoji: '❄️',
    category: 'Природа',
    question: 'Зима для меня — это...',
    optionA: 'Любимое время, обожаю снег',
    optionB: 'Уют, какао, тёплая одежда',
    optionC: 'Терпимо, но жду весну',
    optionD: 'Темно и холодно, ненавижу',
    image: '/images/questions/q112.jpg',
  },
  {
    emoji: '🌧️',
    category: 'Природа',
    question: 'Дождь за окном:',
    optionA: 'Романтика, медитация, любовь',
    optionB: 'Уютно с книгой и чаем',
    optionC: 'Нормально, не люблю особо',
    optionD: 'Депрессия и серость',
    image: '/images/questions/q113.jpg',
  },
  {
    emoji: '🐕',
    category: 'Природа',
    question: 'Если выбирать питомца:',
    optionA: 'Большая активная собака',
    optionB: 'Маленькая ласковая собака',
    optionC: 'Независимый кот',
    optionD: 'Аквариум или птица',
    image: '/images/questions/q114.jpg',
  },
  {
    emoji: '🌄',
    category: 'Природа',
    question: 'Поход в горы на 3 дня:',
    optionA: 'Сразу беру рюкзак — мечта',
    optionB: 'С удовольствием, если подготовлен',
    optionC: 'Только с гидом и комфортом',
    optionD: 'Нет, лучше отель и автобус',
    image: '/images/questions/q115.jpg',
  },
  {
    emoji: '🦋',
    category: 'Природа',
    question: 'Насекомые в комнате:',
    optionA: 'Спокойно выношу на улицу',
    optionB: 'Без эмоций смахну в окно',
    optionC: 'Неприятно, но справлюсь',
    optionD: 'В панике, зову на помощь',
    image: '/images/questions/q116.jpg',
  },
  {
    emoji: '🏞️',
    category: 'Природа',
    question: 'Пикник за городом:',
    optionA: 'Каждые выходные летом',
    optionB: 'Раз в месяц, с удовольствием',
    optionC: 'Иногда, по особому поводу',
    optionD: 'Лучше терраса ресторана',
    image: '/images/questions/q117.jpg',
  },
  {
    emoji: '🌊',
    category: 'Природа',
    question: 'Купаться я люблю:',
    optionA: 'В океане, в холодной воде',
    optionB: 'В море, любой температуры',
    optionC: 'В тёплом озере или реке',
    optionD: 'Только в подогретом бассейне',
    image: '/images/questions/q118.jpg',
  },
  {
    emoji: '🌌',
    category: 'Природа',
    question: 'Ночью на природе:',
    optionA: 'Лежу и смотрю на звёзды часами',
    optionB: 'У костра в компании, тепло и душевно',
    optionC: 'В палатке, немного не по себе',
    optionD: 'Страшно, скорее бы домой',
    image: '/images/questions/q119.jpg',
  },

  // --- 13. Мечты ---
  {
    emoji: '🌟',
    category: 'Мечты',
    question: 'Главная мечта жизни:',
    optionA: 'Создать что-то великое, изменить мир',
    optionB: 'Стать признанным в своей сфере',
    optionC: 'Счастливая семья и любимое дело',
    optionD: 'Спокойствие, гармония и тишина',
    image: '/images/questions/q120.jpg',
  },
  {
    emoji: '🏝️',
    category: 'Мечты',
    question: 'Выиграл миллион — что делаю?',
    optionA: 'Сразу кругосветка и впечатления',
    optionB: 'Половину на жизнь, половину инвестирую',
    optionC: 'Покупаю дом и инвестирую',
    optionD: 'Откладываю и продолжаю как раньше',
    image: '/images/questions/q121.jpg',
  },
  {
    emoji: '📝',
    category: 'Мечты',
    question: 'У меня есть список мечт?',
    optionA: 'Веду подробный список с датами',
    optionB: 'Есть список, иногда обновляю',
    optionC: 'Всё в голове, без записей',
    optionD: 'Не задумываюсь о мечтах',
    image: '/images/questions/q122.jpg',
  },
  {
    emoji: '🌍',
    category: 'Мечты',
    question: 'Если жить вечно молодым:',
    optionA: 'Сразу подписался — мечта',
    optionB: 'Да, но с правом выбора потом',
    optionC: 'Сомневаюсь, надо подумать',
    optionD: 'Нет, всё хорошо в своё время',
    image: '/images/questions/q123.jpg',
  },
  {
    emoji: '⏳',
    category: 'Мечты',
    question: 'Что важнее в жизни?',
    optionA: 'Сам путь и процесс',
    optionB: 'Процесс важнее, но результат тоже',
    optionC: 'Результат важнее, но процесс ценю',
    optionD: 'Только результат и достижения',
    image: '/images/questions/q124.jpg',
  },
  {
    emoji: '🚀',
    category: 'Мечты',
    question: 'Полёт в космос — поехал бы?',
    optionA: 'Хоть завтра, давно мечтаю',
    optionB: 'Да, если технологии безопасны',
    optionC: 'Подумал бы, но скорее нет',
    optionD: 'Ни за что, дома лучше',
    image: '/images/questions/q125.jpg',
  },
  {
    emoji: '🎨',
    category: 'Мечты',
    question: 'Если бы не работа сейчас, я бы...',
    optionA: 'Открыл своё дело прямо завтра',
    optionB: 'Год учился новой профессии',
    optionC: 'Год путешествовал по миру',
    optionD: 'Просто отдыхал и наслаждался жизнью',
    image: '/images/questions/q126.jpg',
  },
  {
    emoji: '🏆',
    category: 'Мечты',
    question: 'Через 20 лет хочется...',
    optionA: 'Финансовую свободу и раннюю пенсию',
    optionB: 'Большие достижения и наследие',
    optionC: 'Любимое дело и стабильность',
    optionD: 'Семью, дом и спокойствие',
    image: '/images/questions/q127.jpg',
  },
  {
    emoji: '🎭',
    category: 'Мечты',
    question: 'Стать знаменитым — мечтаешь?',
    optionA: 'Да, хочу быть известным во всём мире',
    optionB: 'Признание в своей сфере — да',
    optionC: 'Узнаваемость в узком кругу хватит',
    optionD: 'Нет, ценю приватность превыше всего',
    image: '/images/questions/q128.jpg',
  },
  {
    emoji: '🧬',
    category: 'Мечты',
    question: 'Если бы дали суперспособность:',
    optionA: 'Путешествовать во времени',
    optionB: 'Останавливать время',
    optionC: 'Читать мысли других',
    optionD: 'Лечить любые болезни',
    image: '/images/questions/q129.jpg',
  },

  // --- 14. Страхи и риски ---
  {
    emoji: '😱',
    category: 'Страхи и риски',
    question: 'Прыгнуть с парашютом:',
    optionA: 'Хоть сейчас, обожаю экстрим',
    optionB: 'Да, если уговорят и подготовят',
    optionC: 'Скорее нет, страшно',
    optionD: 'Никогда в жизни',
    image: '/images/questions/q130.jpg',
  },
  {
    emoji: '🕷️',
    category: 'Страхи и риски',
    question: 'Самый большой страх:',
    optionA: 'Высота и полёты',
    optionB: 'Замкнутые пространства',
    optionC: 'Толпа и публичные выступления',
    optionD: 'Одиночество и темнота',
    image: '/images/questions/q131.jpg',
  },
  {
    emoji: '🦈',
    category: 'Страхи и риски',
    question: 'Плавать в открытом океане:',
    optionA: 'Захватывающе, давно мечтаю',
    optionB: 'Интересно, если рядом гид',
    optionC: 'Немного боюсь, но попробую',
    optionD: 'Страшно, там кто-то есть',
    image: '/images/questions/q132.jpg',
  },
  {
    emoji: '🎢',
    category: 'Страхи и риски',
    question: 'Экстремальные виды отдыха:',
    optionA: 'Адреналин — это жизнь',
    optionB: 'Иногда хочется встряски',
    optionC: 'Только лёгкий экстрим',
    optionD: 'Спасибо, я понаблюдаю',
    image: '/images/questions/q133.jpg',
  },
  {
    emoji: '🎤',
    category: 'Страхи и риски',
    question: 'Выступать перед публикой:',
    optionA: 'Обожаю быть в центре внимания',
    optionB: 'Спокойно, привычно',
    optionC: 'Волнительно, но справлюсь',
    optionD: 'Ужас, ноги ватные',
    image: '/images/questions/q134.jpg',
  },
  {
    emoji: '🌑',
    category: 'Страхи и риски',
    question: 'Страх темноты:',
    optionA: 'Темнота — мой друг, обожаю',
    optionB: 'Сплю без ночника, нормально',
    optionC: 'Лучше с подсветкой в коридоре',
    optionD: 'Обязательно ночник в комнате',
    image: '/images/questions/q135.jpg',
  },
  {
    emoji: '🐶',
    category: 'Страхи и риски',
    question: 'Большая собака бежит навстречу:',
    optionA: 'Сразу к ней — гладить и сюсюкать',
    optionB: 'Спокойно жду, потом глажу',
    optionC: 'Напрягаюсь, но не убегаю',
    optionD: 'Перехожу на другую сторону',
    image: '/images/questions/q136.jpg',
  },
  {
    emoji: '🦷',
    category: 'Страхи и риски',
    question: 'Поход к стоматологу:',
    optionA: 'Хожу по плану, всё ок',
    optionB: 'Спокойно, но особо не люблю',
    optionC: 'Откладываю, но иду когда болит',
    optionD: 'Откладываю до последнего, паника',
    image: '/images/questions/q137.jpg',
  },
  {
    emoji: '📞',
    category: 'Страхи и риски',
    question: 'Звонить незнакомым по телефону:',
    optionA: 'Без проблем, набираю и говорю',
    optionB: 'Спокойно, если знаю что сказать',
    optionC: 'Стрессую, готовлюсь заранее',
    optionD: 'Никогда, только сообщения',
    image: '/images/questions/q138.jpg',
  },
  {
    emoji: '🎲',
    category: 'Страхи и риски',
    question: 'Риск в жизни — это...',
    optionA: 'Двигатель, без него скучно',
    optionB: 'Норма, иногда нужно рискнуть',
    optionC: 'Только обдуманный риск',
    optionD: 'Опасно, выбираю стабильность',
    image: '/images/questions/q139.jpg',
  },

  // --- 15. Семья ---
  {
    emoji: '👨‍👩‍👧',
    category: 'Семья',
    question: 'Сколько детей хочу:',
    optionA: 'Большая семья — 4 и больше',
    optionB: 'Двое-трое детей',
    optionC: 'Один ребёнок — достаточно',
    optionD: 'Без детей, и так хорошо',
    image: '/images/questions/q140.jpg',
  },
  {
    emoji: '🏡',
    category: 'Семья',
    question: 'Как часто общаюсь с родителями?',
    optionA: 'Каждый день, очень близко',
    optionB: 'Несколько раз в неделю',
    optionC: 'Раз в неделю-две',
    optionD: 'Редко, по большим поводам',
    image: '/images/questions/q141.jpg',
  },
  {
    emoji: '🎄',
    category: 'Семья',
    question: 'Семейные традиции на праздники:',
    optionA: 'Святое, повторяю каждый год',
    optionB: 'Важны, но иногда меняю',
    optionC: 'Иногда соблюдаю, иногда нет',
    optionD: 'Не люблю обязаловку, по настроению',
    image: '/images/questions/q142.jpg',
  },
  {
    emoji: '🚸',
    category: 'Семья',
    question: 'Воспитание детей — это...',
    optionA: 'Строгая дисциплина и правила',
    optionB: 'Чёткие границы, но с диалогом',
    optionC: 'Свобода в рамках разумного',
    optionD: 'Полное доверие, ребёнок сам решает',
    image: '/images/questions/q143.jpg',
  },
  {
    emoji: '👵',
    category: 'Семья',
    question: 'Старшие родственники в семье:',
    optionA: 'Живут с нами, забочусь лично',
    optionB: 'Живут рядом, помогаю ежедневно',
    optionC: 'Своя жизнь, мы часто навещаем',
    optionD: 'Каждый сам по себе, видимся редко',
    image: '/images/questions/q144.jpg',
  },
  {
    emoji: '🎂',
    category: 'Семья',
    question: 'Дни рождения родственников:',
    optionA: 'Помню всех, готовлю подарки заранее',
    optionB: 'Помню большинство, поздравляю',
    optionC: 'Календарь напоминает',
    optionD: 'Постоянно забываю, потом извиняюсь',
    image: '/images/questions/q145.jpg',
  },
  {
    emoji: '🍲',
    category: 'Семья',
    question: 'Воскресный обед всей семьёй:',
    optionA: 'Каждую неделю, святое',
    optionB: 'Пару раз в месяц обязательно',
    optionC: 'По большим праздникам',
    optionD: 'Очень редко, нет такой традиции',
    image: '/images/questions/q146.jpg',
  },
  {
    emoji: '👶',
    category: 'Семья',
    question: 'Заводить детей лучше...',
    optionA: 'Очень рано, до 25',
    optionB: 'Молодым, в 25-30',
    optionC: 'После 30, когда всё построено',
    optionD: 'Когда сам уже зрелый, за 35',
    image: '/images/questions/q147.jpg',
  },
  {
    emoji: '🧬',
    category: 'Семья',
    question: 'Семейные секреты:',
    optionA: 'Никаких секретов, всё открыто',
    optionB: 'Делюсь почти всем с близкими',
    optionC: 'Есть личное, что не для всех',
    optionD: 'Личное — это моё, и точка',
    image: '/images/questions/q148.jpg',
  },
  {
    emoji: '✈️',
    category: 'Семья',
    question: 'Совместный отпуск с родителями:',
    optionA: 'С удовольствием, каждый год',
    optionB: 'Иногда, по особому поводу',
    optionC: 'Редко, мы по-разному отдыхаем',
    optionD: 'Лучше отдельно, каждый сам',
    image: '/images/questions/q149.jpg',
  },

  // --- 16. Стиль и внешность ---
  {
    emoji: '👗',
    category: 'Стиль и внешность',
    question: 'Мой стиль одежды:',
    optionA: 'Яркий и заметный, эксперименты',
    optionB: 'Стильный, слежу за трендами',
    optionC: 'Базовый, классический, нейтральный',
    optionD: 'Спортивный, главное удобство',
    image: '/images/questions/q150.jpg',
  },
  {
    emoji: '💅',
    category: 'Стиль и внешность',
    question: 'Уход за собой:',
    optionA: 'Целый сложный ритуал каждый день',
    optionB: 'Регулярный уход, всё по плану',
    optionC: 'Базовый уход, без излишеств',
    optionD: 'Душ и крем — всё что нужно',
    image: '/images/questions/q151.jpg',
  },
  {
    emoji: '👠',
    category: 'Стиль и внешность',
    question: 'Обувь на каждый день:',
    optionA: 'Спортивные кроссовки, главное удобство',
    optionB: 'Стильные кеды или мокасины',
    optionC: 'Классические туфли или ботинки',
    optionD: 'Каблуки или дизайнерская обувь',
    image: '/images/questions/q152.jpg',
  },
  {
    emoji: '✂️',
    category: 'Стиль и внешность',
    question: 'Кардинально сменить стрижку:',
    optionA: 'Раз в пару месяцев, обожаю меняться',
    optionB: 'Раз в полгода точно',
    optionC: 'Раз в год пробую новое',
    optionD: 'Одна стрижка уже 10 лет',
    image: '/images/questions/q153.jpg',
  },
  {
    emoji: '💄',
    category: 'Стиль и внешность',
    question: 'Образ для выхода в свет:',
    optionA: 'Максимум — мейк, укладка, образ',
    optionB: 'Заметный, но не перебор',
    optionC: 'Лёгкий и аккуратный',
    optionD: 'Естественно, как обычно',
    image: '/images/questions/q154.jpg',
  },
  {
    emoji: '🛍️',
    category: 'Стиль и внешность',
    question: 'Мой гардероб:',
    optionA: 'Идеальная капсула, всё сочетается',
    optionB: 'Продуманный, но с любимчиками',
    optionC: 'Достаточно вещей на все случаи',
    optionD: 'Куча всего, шкаф не закрывается',
    image: '/images/questions/q155.jpg',
  },
  {
    emoji: '👜',
    category: 'Стиль и внешность',
    question: 'Брендовые вещи:',
    optionA: 'Только люкс, качество того стоит',
    optionB: 'Известные бренды, по сезонам',
    optionC: 'Иногда что-то брендовое',
    optionD: 'Переплата за лейбл, не моё',
    image: '/images/questions/q156.jpg',
  },
  {
    emoji: '🦷',
    category: 'Стиль и внешность',
    question: 'Время перед зеркалом утром:',
    optionA: 'Час минимум, полный образ',
    optionB: '30-40 минут на всё',
    optionC: '15 минут, всё необходимое',
    optionD: '5 минут и побежал',
    image: '/images/questions/q157.jpg',
  },
  {
    emoji: '🌸',
    category: 'Стиль и внешность',
    question: 'Парфюм у меня:',
    optionA: 'Большая коллекция, по настроению',
    optionB: 'Несколько на сезоны и случаи',
    optionC: 'Один любимый много лет',
    optionD: 'Не пользуюсь парфюмом',
    image: '/images/questions/q158.jpg',
  },
  {
    emoji: '🧴',
    category: 'Стиль и внешность',
    question: 'Покупки косметики и ухода:',
    optionA: 'Каждую новинку хочу попробовать',
    optionB: 'Покупаю регулярно, разное',
    optionC: 'Только проверенное, минимум',
    optionD: 'Мыло и крем, мне хватает',
    image: '/images/questions/q159.jpg',
  },

  // --- 17. Характер ---
  {
    emoji: '🎯',
    category: 'Характер',
    question: 'Решения я принимаю:',
    optionA: 'Мгновенно, на чистой интуиции',
    optionB: 'Быстро, но с проверкой',
    optionC: 'Не спеша, взвешивая варианты',
    optionD: 'Долго анализирую все за и против',
    image: '/images/questions/q160.jpg',
  },
  {
    emoji: '💭',
    category: 'Характер',
    question: 'Когда тяжело, я:',
    optionA: 'Сразу делюсь с близкими, ищу поддержку',
    optionB: 'Рассказываю одному близкому',
    optionC: 'Сначала переживаю сам, потом говорю',
    optionD: 'Закрываюсь и проживаю в одиночестве',
    image: '/images/questions/q161.jpg',
  },
  {
    emoji: '😤',
    category: 'Характер',
    question: 'Когда злюсь, я:',
    optionA: 'Открыто и громко всё высказываю',
    optionB: 'Спокойно, но прямо говорю',
    optionC: 'Молчу, потом обсуждаю спокойно',
    optionD: 'Закрываюсь, ухожу в себя',
    image: '/images/questions/q162.jpg',
  },
  {
    emoji: '🤝',
    category: 'Характер',
    question: 'В конфликте я обычно:',
    optionA: 'Иду до конца, отстаиваю своё',
    optionB: 'Спорю, но готов слушать',
    optionC: 'Ищу компромисс',
    optionD: 'Уступаю ради мира',
    image: '/images/questions/q163.jpg',
  },
  {
    emoji: '🕰️',
    category: 'Характер',
    question: 'Опаздываю ли я на встречи?',
    optionA: 'Всегда прихожу за 15 минут',
    optionB: 'Прихожу ровно вовремя',
    optionC: 'Иногда задерживаюсь на 5 минут',
    optionD: 'Часто опаздываю на 15-30 минут',
    image: '/images/questions/q164.jpg',
  },
  {
    emoji: '🧩',
    category: 'Характер',
    question: 'Перфекционизм во мне:',
    optionA: 'Всё должно быть идеально, иначе никак',
    optionB: 'Стремлюсь к качеству, но без срывов',
    optionC: 'Делаю хорошо, не отлично',
    optionD: 'Главное — сделано, остальное мелочи',
    image: '/images/questions/q165.jpg',
  },
  {
    emoji: '🎪',
    category: 'Характер',
    question: 'Изменения в жизни:',
    optionA: 'Обожаю, постоянно ищу новое',
    optionB: 'Воспринимаю позитивно',
    optionC: 'Привыкаю, нужно время',
    optionD: 'Стресс, нужна стабильность',
    image: '/images/questions/q166.jpg',
  },
  {
    emoji: '🔥',
    category: 'Характер',
    question: 'В новой обстановке:',
    optionA: 'Сразу общаюсь, я как дома',
    optionB: 'Быстро вливаюсь после знакомства',
    optionC: 'Нужно время, чтобы освоиться',
    optionD: 'Сижу в углу и наблюдаю',
    image: '/images/questions/q167.jpg',
  },
  {
    emoji: '🌈',
    category: 'Характер',
    question: 'Стакан наполовину:',
    optionA: 'Полон! Всё будет супер',
    optionB: 'Скорее полон, я оптимист',
    optionC: 'Реалист — что есть, то есть',
    optionD: 'Готовлюсь к худшему',
    image: '/images/questions/q168.jpg',
  },
  {
    emoji: '🎁',
    category: 'Характер',
    question: 'Сюрпризы для меня:',
    optionA: 'Обожаю, мечтаю о неожиданностях',
    optionB: 'Приятно, если знаю что хороший',
    optionC: 'Только маленькие и приятные',
    optionD: 'Лучше знать всё заранее',
    image: '/images/questions/q169.jpg',
  },

  // --- 18. Кино и музыка ---
  {
    emoji: '🎬',
    category: 'Кино и музыка',
    question: 'Любимый жанр кино:',
    optionA: 'Артхаус и сложные драмы',
    optionB: 'Триллеры и детективы',
    optionC: 'Романтические истории',
    optionD: 'Комедии и блокбастеры',
    image: '/images/questions/q170.jpg',
  },
  {
    emoji: '📺',
    category: 'Кино и музыка',
    question: 'Сериалы я смотрю:',
    optionA: 'Запоем, весь сезон за выходные',
    optionB: 'По 2-3 серии за вечер',
    optionC: 'По серии в день, не спеша',
    optionD: 'Раз в неделю, наслаждаюсь',
    image: '/images/questions/q171.jpg',
  },
  {
    emoji: '🎵',
    category: 'Кино и музыка',
    question: 'Музыка дома играет:',
    optionA: 'Всегда, без неё пустота',
    optionB: 'Часто, фоном на кухне',
    optionC: 'Иногда, под настроение',
    optionD: 'Только в наушниках, по делу',
    image: '/images/questions/q172.jpg',
  },
  {
    emoji: '🎸',
    category: 'Кино и музыка',
    question: 'Любимый жанр музыки:',
    optionA: 'Тяжёлый рок и метал',
    optionB: 'Инди и альтернатива',
    optionC: 'Поп и хиты на радио',
    optionD: 'Классика, джаз, лаунж',
    image: '/images/questions/q173.jpg',
  },
  {
    emoji: '🎤',
    category: 'Кино и музыка',
    question: 'Концерт любимого артиста:',
    optionA: 'Первый ряд, фан-зона',
    optionB: 'В толпе перед сценой',
    optionC: 'На фан-зоне средних мест',
    optionD: 'На задних местах, чтобы видеть всё',
    image: '/images/questions/q174.jpg',
  },
  {
    emoji: '🎻',
    category: 'Кино и музыка',
    question: 'Из театра выбираю:',
    optionA: 'Классическая опера и балет',
    optionB: 'Драматический спектакль',
    optionC: 'Мюзикл — весело и зрелищно',
    optionD: 'Стендап или иммерсив',
    image: '/images/questions/q175.jpg',
  },
  {
    emoji: '🍿',
    category: 'Кино и музыка',
    question: 'Поход в кино — это...',
    optionA: 'Большое ведро попкорна и кола',
    optionB: 'Маленький попкорн и напиток',
    optionC: 'Только напиток в руке',
    optionD: 'Без еды, только фильм',
    image: '/images/questions/q176.jpg',
  },
  {
    emoji: '📽️',
    category: 'Кино и музыка',
    question: 'Один и тот же фильм:',
    optionA: 'Пересматриваю любимые десятки раз',
    optionB: 'Часто возвращаюсь к избранным',
    optionC: 'Редко пересматриваю',
    optionD: 'Только новинки, скучно повторять',
    image: '/images/questions/q177.jpg',
  },
  {
    emoji: '🎙️',
    category: 'Кино и музыка',
    question: 'Подкасты в дороге:',
    optionA: 'Каждый день, без них никак',
    optionB: 'Регулярно слушаю любимые',
    optionC: 'Иногда, под настроение',
    optionD: 'Не слушаю, лучше музыку',
    image: '/images/questions/q178.jpg',
  },
  {
    emoji: '🎼',
    category: 'Кино и музыка',
    question: 'Музыкальный инструмент:',
    optionA: 'Играю свободно, выступаю',
    optionB: 'Играю для себя или близких',
    optionC: 'Играл когда-то, могу вспомнить',
    optionD: 'Только слушаю, не играю',
    image: '/images/questions/q179.jpg',
  },

  // --- 19. Философия жизни ---
  {
    emoji: '🕰️',
    category: 'Философия жизни',
    question: 'Жизнь — это...',
    optionA: 'Путешествие, наслаждаемся процессом',
    optionB: 'Сцена, где играем разные роли',
    optionC: 'Школа, в которой учимся',
    optionD: 'Задача, которую нужно решить',
    image: '/images/questions/q180.jpg',
  },
  {
    emoji: '🎯',
    category: 'Философия жизни',
    question: 'Что важнее в жизни?',
    optionA: 'Полная свобода и независимость',
    optionB: 'Свобода в стабильных рамках',
    optionC: 'Безопасность с возможностями',
    optionD: 'Стабильность и предсказуемость',
    image: '/images/questions/q181.jpg',
  },
  {
    emoji: '💡',
    category: 'Философия жизни',
    question: 'Главная ценность для меня:',
    optionA: 'Свобода и впечатления',
    optionB: 'Любовь и отношения',
    optionC: 'Семья и дом',
    optionD: 'Достижения и наследие',
    image: '/images/questions/q182.jpg',
  },
  {
    emoji: '🌱',
    category: 'Философия жизни',
    question: 'Жить надо:',
    optionA: 'Только здесь и сейчас, без планов',
    optionB: 'В моменте, но с целями',
    optionC: 'С прицелом на будущее, но радуясь',
    optionD: 'Строго по плану на годы вперёд',
    image: '/images/questions/q183.jpg',
  },
  {
    emoji: '🤲',
    category: 'Философия жизни',
    question: 'Помогать другим:',
    optionA: 'Постоянно, это моя миссия',
    optionB: 'Часто, мне это нравится',
    optionC: 'Когда могу и хочу',
    optionD: 'Только близким, у каждого своё',
    image: '/images/questions/q184.jpg',
  },
  {
    emoji: '⚖️',
    category: 'Философия жизни',
    question: 'Справедливость или милосердие:',
    optionA: 'Строгая справедливость превыше всего',
    optionB: 'Справедливость с пониманием',
    optionC: 'Милосердие с разумной строгостью',
    optionD: 'Безусловное милосердие',
    image: '/images/questions/q185.jpg',
  },
  {
    emoji: '🌌',
    category: 'Философия жизни',
    question: 'Есть ли судьба?',
    optionA: 'Всё предопределено заранее',
    optionB: 'Есть путь, но выбор за нами',
    optionC: 'Сами творцы, но что-то случается',
    optionD: 'Всё в наших руках, судьбы нет',
    image: '/images/questions/q186.jpg',
  },
  {
    emoji: '🧘',
    category: 'Философия жизни',
    question: 'Счастье — это...',
    optionA: 'Маленькие моменты каждый день',
    optionB: 'Любовь и тёплые отношения',
    optionC: 'Реализация себя в любимом деле',
    optionD: 'Большие победы и достижения',
    image: '/images/questions/q187.jpg',
  },
  {
    emoji: '📜',
    category: 'Философия жизни',
    question: 'Что хочу оставить после себя?',
    optionA: 'Великое творение или открытие',
    optionB: 'Бизнес или дело, что переживёт меня',
    optionC: 'Хороших и счастливых детей',
    optionD: 'Память в сердцах близких',
    image: '/images/questions/q188.jpg',
  },
  {
    emoji: '🪞',
    category: 'Философия жизни',
    question: 'Самокритика во мне:',
    optionA: 'Очень сильная, постоянно ругаю себя',
    optionB: 'Высокая, всегда есть к чему расти',
    optionC: 'Умеренная, в основном принимаю себя',
    optionD: 'Минимальная, принимаю себя любого',
    image: '/images/questions/q189.jpg',
  },

  // --- 20. Парные ситуации ---
  {
    emoji: '💬',
    category: 'Парные ситуации',
    question: 'Когда я уставший, мне нужно:',
    optionA: 'Молчаливые объятия и тишина',
    optionB: 'Чтобы рядом был кто-то близкий',
    optionC: 'Чтобы спросили — но не давили',
    optionD: 'Чтобы дали полностью побыть одному',
    image: '/images/questions/q190.jpg',
  },
  {
    emoji: '🧦',
    category: 'Парные ситуации',
    question: 'Беспорядок в общем доме — моя реакция:',
    optionA: 'Молча убираю, говорить бесполезно',
    optionB: 'Убираю и спокойно обсуждаем',
    optionC: 'Сразу прошу убрать',
    optionD: 'Возмущаюсь и устраиваю разговор',
    image: '/images/questions/q191.jpg',
  },
  {
    emoji: '📱',
    category: 'Парные ситуации',
    question: 'Личное пространство в телефоне:',
    optionA: 'Никаких границ, всё открыто',
    optionB: 'Доверяю и не лезу, но мог бы',
    optionC: 'У каждого свои секреты, это нормально',
    optionD: 'Телефон — это святое, личное',
    image: '/images/questions/q192.jpg',
  },
  {
    emoji: '🗺️',
    category: 'Парные ситуации',
    question: 'Заблудились в новом городе:',
    optionA: 'Иду спрашивать у прохожих',
    optionB: 'Гуглю и иду уверенно по карте',
    optionC: 'Открываем карту и решаем вместе',
    optionD: 'Паникую и хочу домой',
    image: '/images/questions/q193.jpg',
  },
  {
    emoji: '🎁',
    category: 'Парные ситуации',
    question: 'Подарок партнёру на годовщину:',
    optionA: 'Продумываю за месяцы заранее',
    optionB: 'За пару недель ищу идеи',
    optionC: 'За неделю покупаю что подскажут',
    optionD: 'В последний день в магазин',
    image: '/images/questions/q194.jpg',
  },
  {
    emoji: '🍝',
    category: 'Парные ситуации',
    question: 'Совместная готовка для меня:',
    optionA: 'Обожаю, готовим вдвоём всегда',
    optionB: 'Часто, это нас сближает',
    optionC: 'Иногда, по особому поводу',
    optionD: 'Лучше готовить одному, не мешают',
    image: '/images/questions/q195.jpg',
  },
  {
    emoji: '💼',
    category: 'Парные ситуации',
    question: 'Переезд в другую страну ради партнёра:',
    optionA: 'Поеду без раздумий, ради любви',
    optionB: 'Да, если перспективы хорошие',
    optionC: 'Это серьёзный долгий разговор',
    optionD: 'Нет, корни здесь',
    image: '/images/questions/q196.jpg',
  },
  {
    emoji: '🛍️',
    category: 'Парные ситуации',
    question: 'Партнёр купил странную дорогую вещь:',
    optionA: 'Это его деньги, пусть радуется',
    optionB: 'Поинтересуюсь, что за выбор',
    optionC: 'Скажу что думаю, но без скандала',
    optionD: 'Возмутюсь, такое надо обсуждать',
    image: '/images/questions/q197.jpg',
  },
  {
    emoji: '🤐',
    category: 'Парные ситуации',
    question: 'В ссоре я обычно:',
    optionA: 'Первый иду на примирение',
    optionB: 'Быстро остываю и говорю',
    optionC: 'Беру паузу, потом возвращаюсь',
    optionD: 'Жду, пока сделают шаг навстречу',
    image: '/images/questions/q198.jpg',
  },
  {
    emoji: '🛌',
    category: 'Парные ситуации',
    question: 'Спать вдвоём для меня:',
    optionA: 'Только в обнимку, всю ночь',
    optionB: 'Близко, но без объятий всю ночь',
    optionC: 'Рядом, но каждому своё место',
    optionD: 'Отдельные одеяла, иначе не сплю',
    image: '/images/questions/q199.jpg',
  },
]

export function shuffle(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export function randomIndices(n, total) {
  return shuffle(Array.from({ length: total }, (_, i) => i)).slice(0, n)
}
