export const ALL_QUESTIONS = [
  // --- 1. Путешествия ---
  {
    emoji: '✈️',
    category: 'Путешествия',
    question: 'Куда бы ты полетел прямо сейчас?',
    optionA: 'Тёплое море и пляж',
    optionB: 'Горы и активный отдых',
    image: '/images/questions/q000.jpg',
  },
  {
    emoji: '🏕️',
    category: 'Путешествия',
    question: 'Идеальный отдых — это...',
    optionA: 'Палатка в лесу без связи',
    optionB: 'Отель 5 звёзд с бассейном',
    image: '/images/questions/q001.jpg',
  },
  {
    emoji: '🗺️',
    category: 'Путешествия',
    question: 'Как ты планируешь поездки?',
    optionA: 'Спонтанно, без плана',
    optionB: 'Всё расписано по часам',
    image: '/images/questions/q002.jpg',
  },
  {
    emoji: '🌍',
    category: 'Путешествия',
    question: 'Переехать жить в другую страну?',
    optionA: 'Да, давно мечтаю',
    optionB: 'Нет, дома лучше',
    image: '/images/questions/q003.jpg',
  },
  {
    emoji: '🏙️',
    category: 'Путешествия',
    question: 'Где комфортнее жить?',
    optionA: 'Большой шумный город',
    optionB: 'Тихий пригород',
    image: '/images/questions/q004.jpg',
  },
  {
    emoji: '🚐',
    category: 'Путешествия',
    question: 'Год в путешествиях — как?',
    optionA: 'В фургоне по Европе',
    optionB: 'Зимовка на одном острове',
    image: '/images/questions/q005.jpg',
  },
  {
    emoji: '🛂',
    category: 'Путешествия',
    question: 'Лучше один отпуск...',
    optionA: 'Длинный, на 3 недели',
    optionB: 'Три коротких по неделе',
    image: '/images/questions/q006.jpg',
  },
  {
    emoji: '🧳',
    category: 'Путешествия',
    question: 'Чемодан для путешествия:',
    optionA: 'Минимум вещей, всё налегке',
    optionB: 'На все случаи жизни',
    image: '/images/questions/q007.jpg',
  },
  {
    emoji: '🗾',
    category: 'Путешествия',
    question: 'Куда хочется уехать впервые?',
    optionA: 'В Японию — необычная культура',
    optionB: 'В Италию — еда и история',
    image: '/images/questions/q008.jpg',
  },
  {
    emoji: '🚆',
    category: 'Путешествия',
    question: 'На чём приятнее путешествовать?',
    optionA: 'Поездом, чтобы видеть пейзажи',
    optionB: 'Самолётом — быстрее на месте',
    image: '/images/questions/q009.jpg',
  },

  // --- 2. Еда и кухня ---
  {
    emoji: '🍕',
    category: 'Еда и кухня',
    question: 'Вечер пятницы — что заказываем?',
    optionA: 'Пицца дома и сериал',
    optionB: 'Идём в ресторан',
    image: '/images/questions/q010.jpg',
  },
  {
    emoji: '🌶️',
    category: 'Еда и кухня',
    question: 'Острая еда — это...',
    optionA: 'Чем острее, тем вкуснее',
    optionB: 'Не выношу остроту',
    image: '/images/questions/q011.jpg',
  },
  {
    emoji: '🍳',
    category: 'Еда и кухня',
    question: 'Кто чаще готовит дома?',
    optionA: 'Готовлю с удовольствием сам',
    optionB: 'Лучше закажем доставку',
    image: '/images/questions/q012.jpg',
  },
  {
    emoji: '🥗',
    category: 'Еда и кухня',
    question: 'Твоё отношение к овощам:',
    optionA: 'Половина тарелки — салат',
    optionB: 'Только как гарнир к мясу',
    image: '/images/questions/q013.jpg',
  },
  {
    emoji: '☕',
    category: 'Еда и кухня',
    question: 'Утренний напиток жизни:',
    optionA: 'Крепкий кофе без сахара',
    optionB: 'Чай с молоком и мёдом',
    image: '/images/questions/q014.jpg',
  },
  {
    emoji: '🍰',
    category: 'Еда и кухня',
    question: 'Десерт — это...',
    optionA: 'Обязательно после каждого ужина',
    optionB: 'Только по особым поводам',
    image: '/images/questions/q015.jpg',
  },
  {
    emoji: '🍣',
    category: 'Еда и кухня',
    question: 'На свидание в новый ресторан:',
    optionA: 'Суши и азиатская кухня',
    optionB: 'Стейк и итальянское вино',
    image: '/images/questions/q016.jpg',
  },
  {
    emoji: '🍔',
    category: 'Еда и кухня',
    question: 'Фастфуд в твоей жизни:',
    optionA: 'Иногда можно, это вкусно',
    optionB: 'Не ем уже давно',
    image: '/images/questions/q017.jpg',
  },
  {
    emoji: '🥩',
    category: 'Еда и кухня',
    question: 'Мог бы стать вегетарианцем?',
    optionA: 'Легко, мясо не главное',
    optionB: 'Без мяса жизнь не та',
    image: '/images/questions/q018.jpg',
  },
  {
    emoji: '🍷',
    category: 'Еда и кухня',
    question: 'Вечером бокал чего?',
    optionA: 'Сухое красное вино',
    optionB: 'Холодное пиво или сидр',
    image: '/images/questions/q019.jpg',
  },

  // --- 3. Утро и вечер ---
  {
    emoji: '🌅',
    category: 'Утро и вечер',
    question: 'Кто ты по биоритмам?',
    optionA: 'Жаворонок — встаю рано',
    optionB: 'Сова — оживаю к ночи',
    image: '/images/questions/q020.jpg',
  },
  {
    emoji: '⏰',
    category: 'Утро и вечер',
    question: 'Будильник звонит — что делаешь?',
    optionA: 'Встаю сразу, без отложений',
    optionB: 'Ещё 10 минут, потом ещё 10',
    image: '/images/questions/q021.jpg',
  },
  {
    emoji: '🛏️',
    category: 'Утро и вечер',
    question: 'Идеальное утро начинается с...',
    optionA: 'Тишины и кофе в одиночестве',
    optionB: 'Бодрого разговора и музыки',
    image: '/images/questions/q022.jpg',
  },
  {
    emoji: '🌙',
    category: 'Утро и вечер',
    question: 'Перед сном ты...',
    optionA: 'Читаешь бумажную книгу',
    optionB: 'Скроллишь телефон',
    image: '/images/questions/q023.jpg',
  },
  {
    emoji: '🚿',
    category: 'Утро и вечер',
    question: 'Душ принимаешь...',
    optionA: 'Только утром, чтобы проснуться',
    optionB: 'Только вечером, чтобы расслабиться',
    image: '/images/questions/q024.jpg',
  },
  {
    emoji: '🍳',
    category: 'Утро и вечер',
    question: 'Завтрак — это...',
    optionA: 'Святое, без него никуда',
    optionB: 'Можно пропустить',
    image: '/images/questions/q025.jpg',
  },
  {
    emoji: '😴',
    category: 'Утро и вечер',
    question: 'Сколько часов нужно для жизни?',
    optionA: '6 часов — мне хватает',
    optionB: 'Минимум 8, иначе зомби',
    image: '/images/questions/q026.jpg',
  },
  {
    emoji: '🌃',
    category: 'Утро и вечер',
    question: 'Лучшее время суток:',
    optionA: 'Рассвет — мир ещё спит',
    optionB: 'Поздний вечер — все легли',
    image: '/images/questions/q027.jpg',
  },
  {
    emoji: '🛋️',
    category: 'Утро и вечер',
    question: 'Выходное утро проводишь...',
    optionA: 'В кровати до полудня',
    optionB: 'На пробежке в 7 утра',
    image: '/images/questions/q028.jpg',
  },
  {
    emoji: '🕯️',
    category: 'Утро и вечер',
    question: 'Вечерний ритуал — это...',
    optionA: 'Ванна, свечи, тишина',
    optionB: 'Сериал и чипсы под пледом',
    image: '/images/questions/q029.jpg',
  },

  // --- 4. Деньги и финансы ---
  {
    emoji: '💰',
    category: 'Деньги и финансы',
    question: 'Получил премию — что делаешь?',
    optionA: 'Откладываю на будущее',
    optionB: 'Трачу на что-то приятное',
    image: '/images/questions/q030.jpg',
  },
  {
    emoji: '📊',
    category: 'Деньги и финансы',
    question: 'Бюджет ты ведёшь?',
    optionA: 'Каждый рубль учтён в приложении',
    optionB: 'На глаз, главное не уйти в минус',
    image: '/images/questions/q031.jpg',
  },
  {
    emoji: '🏦',
    category: 'Деньги и финансы',
    question: 'Подушка безопасности:',
    optionA: 'Минимум на 6 месяцев жизни',
    optionB: 'А что это такое?',
    image: '/images/questions/q032.jpg',
  },
  {
    emoji: '💎',
    category: 'Деньги и финансы',
    question: 'Дорогая покупка — твой принцип:',
    optionA: 'Лучше реже, но качественнее',
    optionB: 'Дёшево и часто меняю',
    image: '/images/questions/q033.jpg',
  },
  {
    emoji: '🎁',
    category: 'Деньги и финансы',
    question: 'Подарки любишь...',
    optionA: 'Дарить — больше, чем получать',
    optionB: 'Получать — это так приятно',
    image: '/images/questions/q034.jpg',
  },
  {
    emoji: '🏠',
    category: 'Деньги и финансы',
    question: 'Большая мечта на деньги:',
    optionA: 'Купить свой дом',
    optionB: 'Путешествовать по всему миру',
    image: '/images/questions/q035.jpg',
  },
  {
    emoji: '📈',
    category: 'Деньги и финансы',
    question: 'Инвестиции — это...',
    optionA: 'Активно изучаю и вкладываю',
    optionB: 'Слишком сложно, держу в банке',
    image: '/images/questions/q036.jpg',
  },
  {
    emoji: '🛍️',
    category: 'Деньги и финансы',
    question: 'Шопинг для тебя:',
    optionA: 'Терапия и удовольствие',
    optionB: 'Только по необходимости',
    image: '/images/questions/q037.jpg',
  },
  {
    emoji: '💳',
    category: 'Деньги и финансы',
    question: 'Кредиты — твоё мнение:',
    optionA: 'Можно, если выгодно',
    optionB: 'Только наличные, никаких долгов',
    image: '/images/questions/q038.jpg',
  },
  {
    emoji: '🤝',
    category: 'Деньги и финансы',
    question: 'Семейный бюджет лучше...',
    optionA: 'Общий, всё в одну корзину',
    optionB: 'Раздельный, каждый сам',
    image: '/images/questions/q039.jpg',
  },

  // --- 5. Карьера и амбиции ---
  {
    emoji: '💼',
    category: 'Карьера и амбиции',
    question: 'Работа в твоей жизни:',
    optionA: 'Любимое дело, смысл жизни',
    optionB: 'Способ зарабатывать деньги',
    image: '/images/questions/q040.jpg',
  },
  {
    emoji: '🚀',
    category: 'Карьера и амбиции',
    question: 'Где видишь себя через 5 лет?',
    optionA: 'Свой бизнес, свобода',
    optionB: 'Топ-должность в большой компании',
    image: '/images/questions/q041.jpg',
  },
  {
    emoji: '🏖️',
    category: 'Карьера и амбиции',
    question: 'Идеальный баланс работы и жизни:',
    optionA: 'Работа 4 часа в день, остальное жизнь',
    optionB: 'Работа — это жизнь, мне нравится',
    image: '/images/questions/q042.jpg',
  },
  {
    emoji: '🏡',
    category: 'Карьера и амбиции',
    question: 'Где лучше работается?',
    optionA: 'Из дома в пижаме',
    optionB: 'В офисе среди коллег',
    image: '/images/questions/q043.jpg',
  },
  {
    emoji: '🎓',
    category: 'Карьера и амбиции',
    question: 'Учиться новому ты любишь?',
    optionA: 'Постоянно, курсы и книги',
    optionB: 'Достаточно того, что знаю',
    image: '/images/questions/q044.jpg',
  },
  {
    emoji: '🤐',
    category: 'Карьера и амбиции',
    question: 'Уволиться без плана Б — мог бы?',
    optionA: 'Да, если очень плохо',
    optionB: 'Нет, сначала найду новое',
    image: '/images/questions/q045.jpg',
  },
  {
    emoji: '👔',
    category: 'Карьера и амбиции',
    question: 'Стиль работы:',
    optionA: 'Лидер, который ведёт за собой',
    optionB: 'Исполнитель, который делает идеально',
    image: '/images/questions/q046.jpg',
  },
  {
    emoji: '🧠',
    category: 'Карьера и амбиции',
    question: 'Что важнее в работе?',
    optionA: 'Высокая зарплата',
    optionB: 'Интересные задачи',
    image: '/images/questions/q047.jpg',
  },
  {
    emoji: '✏️',
    category: 'Карьера и амбиции',
    question: 'Профессия мечты — это та, где...',
    optionA: 'Творчество и свобода',
    optionB: 'Стабильность и понятность',
    image: '/images/questions/q048.jpg',
  },
  {
    emoji: '📅',
    category: 'Карьера и амбиции',
    question: 'Отпуск ты берёшь...',
    optionA: 'Все дни, до последнего',
    optionB: 'Часть остаётся неиспользованной',
    image: '/images/questions/q049.jpg',
  },

  // --- 6. Дом и уют ---
  {
    emoji: '🏠',
    category: 'Дом и уют',
    question: 'Идеальное жильё мечты:',
    optionA: 'Дом с садом за городом',
    optionB: 'Квартира в центре города',
    image: '/images/questions/q050.jpg',
  },
  {
    emoji: '🧹',
    category: 'Дом и уют',
    question: 'Дома у тебя обычно:',
    optionA: 'Идеальный порядок всегда',
    optionB: 'Творческий беспорядок',
    image: '/images/questions/q051.jpg',
  },
  {
    emoji: '🛋️',
    category: 'Дом и уют',
    question: 'Стиль интерьера:',
    optionA: 'Минимализм и простор',
    optionB: 'Уютно и много деталей',
    image: '/images/questions/q052.jpg',
  },
  {
    emoji: '🪴',
    category: 'Дом и уют',
    question: 'Растения дома:',
    optionA: 'Целые джунгли на подоконниках',
    optionB: 'Один кактус и тот вянет',
    image: '/images/questions/q053.jpg',
  },
  {
    emoji: '🐕',
    category: 'Дом и уют',
    question: 'Питомец дома:',
    optionA: 'Обязательно нужен пушистик',
    optionB: 'Без животных свободнее',
    image: '/images/questions/q054.jpg',
  },
  {
    emoji: '🧺',
    category: 'Дом и уют',
    question: 'Стирка и уборка:',
    optionA: 'По расписанию, каждую субботу',
    optionB: 'Когда уже невозможно дальше',
    image: '/images/questions/q055.jpg',
  },
  {
    emoji: '🍽️',
    category: 'Дом и уют',
    question: 'Едите дома:',
    optionA: 'За столом, с тарелками',
    optionB: 'На диване перед экраном',
    image: '/images/questions/q056.jpg',
  },
  {
    emoji: '🔔',
    category: 'Дом и уют',
    question: 'Гости в доме:',
    optionA: 'Чем чаще, тем лучше',
    optionB: 'Только по приглашению заранее',
    image: '/images/questions/q057.jpg',
  },
  {
    emoji: '🌡️',
    category: 'Дом и уют',
    question: 'Температура в комнате:',
    optionA: 'Прохладно, открытое окно',
    optionB: 'Тепло, плед и обогреватель',
    image: '/images/questions/q058.jpg',
  },
  {
    emoji: '🛏️',
    category: 'Дом и уют',
    question: 'Кровать утром:',
    optionA: 'Всегда заправляю',
    optionB: 'Зачем, всё равно лягу',
    image: '/images/questions/q059.jpg',
  },

  // --- 7. Друзья и общение ---
  {
    emoji: '🥂',
    category: 'Друзья и общение',
    question: 'Пятница вечером:',
    optionA: 'Большая компания и бар',
    optionB: 'Тихий вечер с одним другом',
    image: '/images/questions/q060.jpg',
  },
  {
    emoji: '🤐',
    category: 'Друзья и общение',
    question: 'Ты по натуре:',
    optionA: 'Экстраверт, заряжаюсь от людей',
    optionB: 'Интроверт, восстанавливаюсь один',
    image: '/images/questions/q061.jpg',
  },
  {
    emoji: '📱',
    category: 'Друзья и общение',
    question: 'Звонок от друга в субботу:',
    optionA: 'Беру с удовольствием',
    optionB: 'Лучше напишу ему позже',
    image: '/images/questions/q062.jpg',
  },
  {
    emoji: '👫',
    category: 'Друзья и общение',
    question: 'Друзей у тебя:',
    optionA: 'Много и разных',
    optionB: 'Мало, но самые близкие',
    image: '/images/questions/q063.jpg',
  },
  {
    emoji: '🎂',
    category: 'Друзья и общение',
    question: 'Свой день рождения:',
    optionA: 'Большая шумная вечеринка',
    optionB: 'Тихий ужин с самыми близкими',
    image: '/images/questions/q064.jpg',
  },
  {
    emoji: '💬',
    category: 'Друзья и общение',
    question: 'Чтобы что-то обсудить, ты...',
    optionA: 'Звонишь и говоришь часами',
    optionB: 'Пишешь — так удобнее',
    image: '/images/questions/q065.jpg',
  },
  {
    emoji: '🎉',
    category: 'Друзья и общение',
    question: 'Корпоративы и тусовки:',
    optionA: 'Обожаю, душа компании',
    optionB: 'Прихожу и уезжаю первым',
    image: '/images/questions/q066.jpg',
  },
  {
    emoji: '🤝',
    category: 'Друзья и общение',
    question: 'Новые знакомства:',
    optionA: 'Легко завожу хоть в очереди',
    optionB: 'Сложно, нужно время',
    image: '/images/questions/q067.jpg',
  },
  {
    emoji: '🍻',
    category: 'Друзья и общение',
    question: 'Лучшие воспоминания с друзьями:',
    optionA: 'Совместные путешествия',
    optionB: 'Долгие разговоры на кухне',
    image: '/images/questions/q068.jpg',
  },
  {
    emoji: '🚪',
    category: 'Друзья и общение',
    question: 'Друг приехал без предупреждения:',
    optionA: 'Класс, заходи!',
    optionB: 'Лучше бы написал заранее',
    image: '/images/questions/q069.jpg',
  },

  // --- 8. Романтика ---
  {
    emoji: '💌',
    category: 'Романтика',
    question: 'Как ты выражаешь чувства?',
    optionA: 'Словами — говорю всё прямо',
    optionB: 'Делами — заботой и поступками',
    image: '/images/questions/q070.jpg',
  },
  {
    emoji: '🌹',
    category: 'Романтика',
    question: 'Идеальное свидание:',
    optionA: 'Романтический ужин при свечах',
    optionB: 'Активность — каток, квест, поход',
    image: '/images/questions/q071.jpg',
  },
  {
    emoji: '🎁',
    category: 'Романтика',
    question: 'Лучше получать в подарок:',
    optionA: 'Что-то материальное',
    optionB: 'Впечатления и эмоции',
    image: '/images/questions/q072.jpg',
  },
  {
    emoji: '🤗',
    category: 'Романтика',
    question: 'Объятия в течение дня:',
    optionA: 'Чем больше, тем лучше',
    optionB: 'По настроению, не часто',
    image: '/images/questions/q073.jpg',
  },
  {
    emoji: '💋',
    category: 'Романтика',
    question: 'Признания в любви:',
    optionA: 'Говорю каждый день',
    optionB: 'Только по особым моментам',
    image: '/images/questions/q074.jpg',
  },
  {
    emoji: '🎶',
    category: 'Романтика',
    question: 'Песня "о нас" — это...',
    optionA: 'Романтическая баллада',
    optionB: 'Что-то весёлое и танцевальное',
    image: '/images/questions/q075.jpg',
  },
  {
    emoji: '🕯️',
    category: 'Романтика',
    question: 'Романтичный вечер дома:',
    optionA: 'Свечи, ванна и тишина',
    optionB: 'Кино, попкорн и смех',
    image: '/images/questions/q076.jpg',
  },
  {
    emoji: '✉️',
    category: 'Романтика',
    question: 'В разлуке ты предпочитаешь:',
    optionA: 'Длинные голосовые сообщения',
    optionB: 'Видеозвонки часами',
    image: '/images/questions/q077.jpg',
  },
  {
    emoji: '📸',
    category: 'Романтика',
    question: 'Совместные фото в соцсетях:',
    optionA: 'Регулярно, я горжусь',
    optionB: 'Редко, личное не для всех',
    image: '/images/questions/q078.jpg',
  },
  {
    emoji: '👰',
    category: 'Романтика',
    question: 'Свадьба должна быть:',
    optionA: 'Большая и пышная',
    optionB: 'Камерная, только свои',
    image: '/images/questions/q079.jpg',
  },

  // --- 9. Развлечения ---
  {
    emoji: '🎮',
    category: 'Развлечения',
    question: 'Свободный вечер — это...',
    optionA: 'Видеоигры или приставка',
    optionB: 'Настольные игры с друзьями',
    image: '/images/questions/q080.jpg',
  },
  {
    emoji: '📚',
    category: 'Развлечения',
    question: 'Книги читаешь:',
    optionA: 'Несколько в месяц',
    optionB: 'Одну в год, и то по работе',
    image: '/images/questions/q081.jpg',
  },
  {
    emoji: '🎨',
    category: 'Развлечения',
    question: 'Твоё хобби должно быть...',
    optionA: 'Творческим — рисую, пишу, готовлю',
    optionB: 'Активным — спорт, танцы, прогулки',
    image: '/images/questions/q082.jpg',
  },
  {
    emoji: '🎤',
    category: 'Развлечения',
    question: 'Караоке в баре:',
    optionA: 'Первым беру микрофон',
    optionB: 'Лучше уйти в другой бар',
    image: '/images/questions/q083.jpg',
  },
  {
    emoji: '🎬',
    category: 'Развлечения',
    question: 'Фильм смотришь в...',
    optionA: 'В кино, на большом экране',
    optionB: 'Дома, в пижаме и тапочках',
    image: '/images/questions/q084.jpg',
  },
  {
    emoji: '🧩',
    category: 'Развлечения',
    question: 'Дождливый день — что делаешь?',
    optionA: 'Собираю пазл, читаю книгу',
    optionB: 'Иду в торговый центр',
    image: '/images/questions/q085.jpg',
  },
  {
    emoji: '🎲',
    category: 'Развлечения',
    question: 'Настольные игры:',
    optionA: 'Стратегии на 4 часа',
    optionB: 'Быстрые и весёлые',
    image: '/images/questions/q086.jpg',
  },
  {
    emoji: '🃏',
    category: 'Развлечения',
    question: 'Азартные игры:',
    optionA: 'Адреналин — это весело',
    optionB: 'Не понимаю, это пустая трата',
    image: '/images/questions/q087.jpg',
  },
  {
    emoji: '🎢',
    category: 'Развлечения',
    question: 'Парк аттракционов:',
    optionA: 'На все горки, до тошноты',
    optionB: 'Только колесо обозрения',
    image: '/images/questions/q088.jpg',
  },
  {
    emoji: '🪩',
    category: 'Развлечения',
    question: 'Танцпол в клубе:',
    optionA: 'Танцую до утра',
    optionB: 'Стою у бара со стаканом',
    image: '/images/questions/q089.jpg',
  },

  // --- 10. Спорт и здоровье ---
  {
    emoji: '🏃',
    category: 'Спорт и здоровье',
    question: 'Спорт в твоей жизни:',
    optionA: 'Регулярно, минимум 3 раза в неделю',
    optionB: 'Хожу-дышу — уже спорт',
    image: '/images/questions/q090.jpg',
  },
  {
    emoji: '🏋️',
    category: 'Спорт и здоровье',
    question: 'Идеальная тренировка:',
    optionA: 'Тяжёлые веса и потеть',
    optionB: 'Йога, растяжка, дыхание',
    image: '/images/questions/q091.jpg',
  },
  {
    emoji: '🥗',
    category: 'Спорт и здоровье',
    question: 'Здоровое питание:',
    optionA: 'Считаю калории и БЖУ',
    optionB: 'Ем что хочу, главное вкусно',
    image: '/images/questions/q092.jpg',
  },
  {
    emoji: '🚴',
    category: 'Спорт и здоровье',
    question: 'Активность по выходным:',
    optionA: 'Велосипед, ролики, поход',
    optionB: 'Диван, плед, отдых',
    image: '/images/questions/q093.jpg',
  },
  {
    emoji: '💊',
    category: 'Спорт и здоровье',
    question: 'Заболел — твой алгоритм:',
    optionA: 'Сразу к врачу, никаких рисков',
    optionB: 'Чай с мёдом и переждать',
    image: '/images/questions/q094.jpg',
  },
  {
    emoji: '🥛',
    category: 'Спорт и здоровье',
    question: 'Сколько воды пьёшь в день?',
    optionA: 'Минимум 2 литра, контролирую',
    optionB: 'Когда вспомню, тогда и пью',
    image: '/images/questions/q095.jpg',
  },
  {
    emoji: '🏊',
    category: 'Спорт и здоровье',
    question: 'Лучший вид активности:',
    optionA: 'Командный спорт',
    optionB: 'Индивидуальный — бег, плавание',
    image: '/images/questions/q096.jpg',
  },
  {
    emoji: '🧘',
    category: 'Спорт и здоровье',
    question: 'Медитация и осознанность:',
    optionA: 'Практикую регулярно',
    optionB: 'Не моё, скучно сидеть',
    image: '/images/questions/q097.jpg',
  },
  {
    emoji: '🚭',
    category: 'Спорт и здоровье',
    question: 'Вредные привычки:',
    optionA: 'Нет, веду здоровый образ жизни',
    optionB: 'Есть, но я не страдаю',
    image: '/images/questions/q098.jpg',
  },
  {
    emoji: '☀️',
    category: 'Спорт и здоровье',
    question: 'Защита от солнца:',
    optionA: 'SPF каждый день, даже зимой',
    optionB: 'Только на пляже, и то редко',
    image: '/images/questions/q099.jpg',
  },

  // --- 11. Технологии ---
  {
    emoji: '📱',
    category: 'Технологии',
    question: 'Сколько часов в день в телефоне?',
    optionA: 'Меньше 2, контролирую',
    optionB: 'Лучше не знать точно',
    image: '/images/questions/q100.jpg',
  },
  {
    emoji: '🔔',
    category: 'Технологии',
    question: 'Уведомления на телефоне:',
    optionA: 'Все включены, нужно быть в курсе',
    optionB: 'Только избранные приложения',
    image: '/images/questions/q101.jpg',
  },
  {
    emoji: '📸',
    category: 'Технологии',
    question: 'Соцсети для тебя:',
    optionA: 'Активно постю каждый день',
    optionB: 'Только читаю, ничего не выкладываю',
    image: '/images/questions/q102.jpg',
  },
  {
    emoji: '🤖',
    category: 'Технологии',
    question: 'Искусственный интеллект:',
    optionA: 'Использую везде, где можно',
    optionB: 'Боюсь, лучше сам подумаю',
    image: '/images/questions/q103.jpg',
  },
  {
    emoji: '⌚',
    category: 'Технологии',
    question: 'Умные часы на руке:',
    optionA: 'Обязательно, без них никак',
    optionB: 'Обычные часы или вообще без',
    image: '/images/questions/q104.jpg',
  },
  {
    emoji: '🎧',
    category: 'Технологии',
    question: 'Наушники в общественных местах:',
    optionA: 'Всегда — это моя крепость',
    optionB: 'Только в дороге',
    image: '/images/questions/q105.jpg',
  },
  {
    emoji: '💻',
    category: 'Технологии',
    question: 'Apple или Android?',
    optionA: 'Только Apple, экосистема',
    optionB: 'Android, больше свободы',
    image: '/images/questions/q106.jpg',
  },
  {
    emoji: '📺',
    category: 'Технологии',
    question: 'Гаджет, без которого жизни нет:',
    optionA: 'Смартфон',
    optionB: 'Ноутбук',
    image: '/images/questions/q107.jpg',
  },
  {
    emoji: '📵',
    category: 'Технологии',
    question: 'Цифровой детокс — мог бы?',
    optionA: 'Неделю без интернета — легко',
    optionB: 'День без телефона — пытка',
    image: '/images/questions/q108.jpg',
  },
  {
    emoji: '🎮',
    category: 'Технологии',
    question: 'Технологии в отношениях:',
    optionA: 'За столом телефон убираем',
    optionB: 'Скроллим вдвоём — это нормально',
    image: '/images/questions/q109.jpg',
  },

  // --- 12. Природа ---
  {
    emoji: '🌲',
    category: 'Природа',
    question: 'Лес или море?',
    optionA: 'Лес — запах сосны и тишина',
    optionB: 'Море — шум волн и солнце',
    image: '/images/questions/q110.jpg',
  },
  {
    emoji: '🍂',
    category: 'Природа',
    question: 'Любимое время года:',
    optionA: 'Тёплая золотая осень',
    optionB: 'Жаркое яркое лето',
    image: '/images/questions/q111.jpg',
  },
  {
    emoji: '❄️',
    category: 'Природа',
    question: 'Зима для тебя — это...',
    optionA: 'Уют, какао, снежные шапки',
    optionB: 'Темно, холодно, скорее бы весна',
    image: '/images/questions/q112.jpg',
  },
  {
    emoji: '🌧️',
    category: 'Природа',
    question: 'Дождь за окном:',
    optionA: 'Романтика и атмосфера',
    optionB: 'Грустно и серо',
    image: '/images/questions/q113.jpg',
  },
  {
    emoji: '🐕',
    category: 'Природа',
    question: 'Если выбирать питомца:',
    optionA: 'Собака — друг и компаньон',
    optionB: 'Кот — характер и независимость',
    image: '/images/questions/q114.jpg',
  },
  {
    emoji: '🌄',
    category: 'Природа',
    question: 'Поход в горы на 3 дня:',
    optionA: 'Беру рюкзак и вперёд',
    optionB: 'Нет, гостиница и автобус',
    image: '/images/questions/q115.jpg',
  },
  {
    emoji: '🦋',
    category: 'Природа',
    question: 'Насекомые в комнате:',
    optionA: 'Спокойно выношу на улицу',
    optionB: 'В панике зову на помощь',
    image: '/images/questions/q116.jpg',
  },
  {
    emoji: '🏞️',
    category: 'Природа',
    question: 'Пикник за городом:',
    optionA: 'Каждые выходные летом',
    optionB: 'Лучше на террасе ресторана',
    image: '/images/questions/q117.jpg',
  },
  {
    emoji: '🌊',
    category: 'Природа',
    question: 'Купаться ты любишь:',
    optionA: 'В море, даже в холодную воду',
    optionB: 'В бассейне, с подогревом',
    image: '/images/questions/q118.jpg',
  },
  {
    emoji: '🌌',
    category: 'Природа',
    question: 'Ночью на природе:',
    optionA: 'Лежу и смотрю на звёзды часами',
    optionB: 'Скорее бы в палатку, страшно',
    image: '/images/questions/q119.jpg',
  },

  // --- 13. Мечты ---
  {
    emoji: '🌟',
    category: 'Мечты',
    question: 'Главная мечта жизни:',
    optionA: 'Создать что-то своё, изменить мир',
    optionB: 'Счастливая семья и спокойствие',
    image: '/images/questions/q120.jpg',
  },
  {
    emoji: '🏝️',
    category: 'Мечты',
    question: 'Выиграл миллион — что делаешь?',
    optionA: 'Кругосветка и впечатления',
    optionB: 'Покупаю дом и инвестирую',
    image: '/images/questions/q121.jpg',
  },
  {
    emoji: '📝',
    category: 'Мечты',
    question: 'У тебя есть список мечт?',
    optionA: 'Да, веду и вычёркиваю',
    optionB: 'Всё в голове, без записей',
    image: '/images/questions/q122.jpg',
  },
  {
    emoji: '🌍',
    category: 'Мечты',
    question: 'Если жить вечно молодым:',
    optionA: 'Хочу — столько всего попробовать',
    optionB: 'Нет, всё хорошо в своё время',
    image: '/images/questions/q123.jpg',
  },
  {
    emoji: '⏳',
    category: 'Мечты',
    question: 'Что важнее в жизни?',
    optionA: 'Путь и процесс',
    optionB: 'Результат и достижения',
    image: '/images/questions/q124.jpg',
  },
  {
    emoji: '🚀',
    category: 'Мечты',
    question: 'Полёт в космос — поехал бы?',
    optionA: 'Сразу подписался, мечта',
    optionB: 'Ни за что, дома лучше',
    image: '/images/questions/q125.jpg',
  },
  {
    emoji: '🎨',
    category: 'Мечты',
    question: 'Если бы не работа сейчас, ты бы...',
    optionA: 'Открыл своё дело',
    optionB: 'Уехал в путешествие на год',
    image: '/images/questions/q126.jpg',
  },
  {
    emoji: '🏆',
    category: 'Мечты',
    question: 'Через 20 лет хочется...',
    optionA: 'Финансовую свободу и пенсию рано',
    optionB: 'Любимое дело до старости',
    image: '/images/questions/q127.jpg',
  },
  {
    emoji: '🎭',
    category: 'Мечты',
    question: 'Стать знаменитым — мечтаешь?',
    optionA: 'Да, хочу влиять на людей',
    optionB: 'Нет, ценю приватность',
    image: '/images/questions/q128.jpg',
  },
  {
    emoji: '🧬',
    category: 'Мечты',
    question: 'Если бы дали суперспособность:',
    optionA: 'Читать мысли других',
    optionB: 'Останавливать время',
    image: '/images/questions/q129.jpg',
  },

  // --- 14. Страхи и риски ---
  {
    emoji: '😱',
    category: 'Страхи и риски',
    question: 'Прыгнуть с парашютом:',
    optionA: 'Хоть сейчас, давно мечтаю',
    optionB: 'Никогда в жизни',
    image: '/images/questions/q130.jpg',
  },
  {
    emoji: '🕷️',
    category: 'Страхи и риски',
    question: 'Самый большой страх:',
    optionA: 'Высота и полёты',
    optionB: 'Замкнутые пространства',
    image: '/images/questions/q131.jpg',
  },
  {
    emoji: '🦈',
    category: 'Страхи и риски',
    question: 'Плавать в открытом океане:',
    optionA: 'Захватывающе и круто',
    optionB: 'Страшно, там кто-то есть',
    image: '/images/questions/q132.jpg',
  },
  {
    emoji: '🎢',
    category: 'Страхи и риски',
    question: 'Экстремальные виды отдыха:',
    optionA: 'Адреналин — это жизнь',
    optionB: 'Спасибо, я понаблюдаю',
    image: '/images/questions/q133.jpg',
  },
  {
    emoji: '🎤',
    category: 'Страхи и риски',
    question: 'Выступать перед публикой:',
    optionA: 'Обожаю быть в центре',
    optionB: 'Ужас, ноги ватные',
    image: '/images/questions/q134.jpg',
  },
  {
    emoji: '🌑',
    category: 'Страхи и риски',
    question: 'Страх темноты:',
    optionA: 'Сплю без ночника, нормально',
    optionB: 'Обязательно с подсветкой',
    image: '/images/questions/q135.jpg',
  },
  {
    emoji: '🐶',
    category: 'Страхи и риски',
    question: 'Большая собака бежит навстречу:',
    optionA: 'Иду гладить и сюсюкать',
    optionB: 'Перехожу на другую сторону',
    image: '/images/questions/q136.jpg',
  },
  {
    emoji: '🦷',
    category: 'Страхи и риски',
    question: 'Поход к стоматологу:',
    optionA: 'Спокойно, ничего страшного',
    optionB: 'Откладываю до последнего',
    image: '/images/questions/q137.jpg',
  },
  {
    emoji: '📞',
    category: 'Страхи и риски',
    question: 'Звонить незнакомым по телефону:',
    optionA: 'Без проблем, набираю и говорю',
    optionB: 'Стресс, лучше написать',
    image: '/images/questions/q138.jpg',
  },
  {
    emoji: '🎲',
    category: 'Страхи и риски',
    question: 'Риск в жизни — это...',
    optionA: 'Двигатель, без него скучно',
    optionB: 'Опасно, лучше стабильность',
    image: '/images/questions/q139.jpg',
  },

  // --- 15. Семья ---
  {
    emoji: '👨‍👩‍👧',
    category: 'Семья',
    question: 'Большая семья — это...',
    optionA: 'Мечта, минимум трое детей',
    optionB: 'Слишком, одного достаточно',
    image: '/images/questions/q140.jpg',
  },
  {
    emoji: '🏡',
    category: 'Семья',
    question: 'С родителями отношения:',
    optionA: 'Очень близкие, видимся часто',
    optionB: 'Тёплые, но на расстоянии',
    image: '/images/questions/q141.jpg',
  },
  {
    emoji: '🎄',
    category: 'Семья',
    question: 'Семейные традиции на праздники:',
    optionA: 'Святое, нарушать нельзя',
    optionB: 'Каждый год по-новому',
    image: '/images/questions/q142.jpg',
  },
  {
    emoji: '🚸',
    category: 'Семья',
    question: 'Воспитание детей — это...',
    optionA: 'Чёткие границы и правила',
    optionB: 'Свобода и доверие',
    image: '/images/questions/q143.jpg',
  },
  {
    emoji: '👵',
    category: 'Семья',
    question: 'Старшие родственники в семье:',
    optionA: 'Живут с нами или рядом',
    optionB: 'Своя жизнь, мы навещаем',
    image: '/images/questions/q144.jpg',
  },
  {
    emoji: '🎂',
    category: 'Семья',
    question: 'Дни рождения родственников:',
    optionA: 'Помню всех и всегда поздравляю',
    optionB: 'Календарь напоминает',
    image: '/images/questions/q145.jpg',
  },
  {
    emoji: '🍲',
    category: 'Семья',
    question: 'Воскресный обед всей семьёй:',
    optionA: 'Каждую неделю обязательно',
    optionB: 'По большим праздникам',
    image: '/images/questions/q146.jpg',
  },
  {
    emoji: '👶',
    category: 'Семья',
    question: 'Заводить детей лучше...',
    optionA: 'Раньше, пока есть силы',
    optionB: 'Позже, когда всё построено',
    image: '/images/questions/q147.jpg',
  },
  {
    emoji: '🧬',
    category: 'Семья',
    question: 'Семейные секреты и тайны:',
    optionA: 'Всё открыто, никаких секретов',
    optionB: 'Личное лучше оставлять личным',
    image: '/images/questions/q148.jpg',
  },
  {
    emoji: '✈️',
    category: 'Семья',
    question: 'Совместный отпуск с родителями:',
    optionA: 'С удовольствием, весело',
    optionB: 'Отдыхать лучше отдельно',
    image: '/images/questions/q149.jpg',
  },

  // --- 16. Стиль и внешность ---
  {
    emoji: '👗',
    category: 'Стиль и внешность',
    question: 'Стиль одежды:',
    optionA: 'Яркий, заметный, экспериментирую',
    optionB: 'Базовый, нейтральный, удобный',
    image: '/images/questions/q150.jpg',
  },
  {
    emoji: '💅',
    category: 'Стиль и внешность',
    question: 'Уход за собой:',
    optionA: 'Целый ритуал каждый день',
    optionB: 'Душ и крем — всё',
    image: '/images/questions/q151.jpg',
  },
  {
    emoji: '👠',
    category: 'Стиль и внешность',
    question: 'Обувь на каждый день:',
    optionA: 'Кроссовки, удобство важнее',
    optionB: 'Стильные туфли или ботинки',
    image: '/images/questions/q152.jpg',
  },
  {
    emoji: '✂️',
    category: 'Стиль и внешность',
    question: 'Кардинально сменить стрижку:',
    optionA: 'Раз в полгода точно',
    optionB: 'Одна длина уже 10 лет',
    image: '/images/questions/q153.jpg',
  },
  {
    emoji: '💄',
    category: 'Стиль и внешность',
    question: 'Образ для выхода в свет:',
    optionA: 'Полный мейк, укладка, всё на максимум',
    optionB: 'Естественно и расслабленно',
    image: '/images/questions/q154.jpg',
  },
  {
    emoji: '🛍️',
    category: 'Стиль и внешность',
    question: 'Гардероб у тебя:',
    optionA: 'Капсула, всё подобрано',
    optionB: 'Куча всего, шкаф не закрывается',
    image: '/images/questions/q155.jpg',
  },
  {
    emoji: '👜',
    category: 'Стиль и внешность',
    question: 'Брендовые вещи:',
    optionA: 'Качество того стоит',
    optionB: 'Переплата за лейбл',
    image: '/images/questions/q156.jpg',
  },
  {
    emoji: '🦷',
    category: 'Стиль и внешность',
    question: 'Время перед зеркалом утром:',
    optionA: 'Не меньше 30 минут',
    optionB: '5 минут и побежал',
    image: '/images/questions/q157.jpg',
  },
  {
    emoji: '🌸',
    category: 'Стиль и внешность',
    question: 'Парфюм у тебя:',
    optionA: 'Один любимый много лет',
    optionB: 'Разные, по настроению',
    image: '/images/questions/q158.jpg',
  },
  {
    emoji: '🧴',
    category: 'Стиль и внешность',
    question: 'Покупки косметики:',
    optionA: 'Минимум баночек, всё работает',
    optionB: 'Хочется попробовать каждую новинку',
    image: '/images/questions/q159.jpg',
  },

  // --- 17. Характер ---
  {
    emoji: '🎯',
    category: 'Характер',
    question: 'Принимаешь решения ты...',
    optionA: 'Быстро, иду по интуиции',
    optionB: 'Долго, взвешиваю плюсы и минусы',
    image: '/images/questions/q160.jpg',
  },
  {
    emoji: '💭',
    category: 'Характер',
    question: 'Когда тяжело, ты:',
    optionA: 'Делишься с близкими',
    optionB: 'Закрываешься и переживаешь сам',
    image: '/images/questions/q161.jpg',
  },
  {
    emoji: '😤',
    category: 'Характер',
    question: 'Злишься ты...',
    optionA: 'Открыто, сразу всё высказываю',
    optionB: 'Молча, отхожу один',
    image: '/images/questions/q162.jpg',
  },
  {
    emoji: '🤝',
    category: 'Характер',
    question: 'В конфликте ты обычно:',
    optionA: 'Иду до конца, отстаиваю своё',
    optionB: 'Иду на компромисс ради мира',
    image: '/images/questions/q163.jpg',
  },
  {
    emoji: '🕰️',
    category: 'Характер',
    question: 'Опаздываешь на встречи?',
    optionA: 'Никогда, прихожу за 10 минут',
    optionB: 'Часто, всегда чуть позже',
    image: '/images/questions/q164.jpg',
  },
  {
    emoji: '🧩',
    category: 'Характер',
    question: 'Перфекционизм в тебе:',
    optionA: 'Всё должно быть идеально',
    optionB: 'Главное — сделано',
    image: '/images/questions/q165.jpg',
  },
  {
    emoji: '🎪',
    category: 'Характер',
    question: 'Изменения в жизни:',
    optionA: 'Люблю, всегда что-то новое',
    optionB: 'Стресс, нужна стабильность',
    image: '/images/questions/q166.jpg',
  },
  {
    emoji: '🔥',
    category: 'Характер',
    question: 'В новой обстановке:',
    optionA: 'Сразу осваиваюсь и общаюсь',
    optionB: 'Сижу в углу и присматриваюсь',
    image: '/images/questions/q167.jpg',
  },
  {
    emoji: '🌈',
    category: 'Характер',
    question: 'Стакан наполовину:',
    optionA: 'Полон, всё будет отлично',
    optionB: 'Пуст, надо готовиться к худшему',
    image: '/images/questions/q168.jpg',
  },
  {
    emoji: '🎁',
    category: 'Характер',
    question: 'Сюрпризы для тебя:',
    optionA: 'Обожаю, и дарить, и получать',
    optionB: 'Лучше знать заранее всё',
    image: '/images/questions/q169.jpg',
  },

  // --- 18. Кино и музыка ---
  {
    emoji: '🎬',
    category: 'Кино и музыка',
    question: 'Любимый жанр кино:',
    optionA: 'Драмы и арт-хаус',
    optionB: 'Комедии и блокбастеры',
    image: '/images/questions/q170.jpg',
  },
  {
    emoji: '📺',
    category: 'Кино и музыка',
    question: 'Сериалы ты смотришь:',
    optionA: 'Запоем, весь сезон за выходные',
    optionB: 'По серии в неделю, наслаждаюсь',
    image: '/images/questions/q171.jpg',
  },
  {
    emoji: '🎵',
    category: 'Кино и музыка',
    question: 'Музыка дома играет:',
    optionA: 'Почти всегда, фоном',
    optionB: 'Только в наушниках, по делу',
    image: '/images/questions/q172.jpg',
  },
  {
    emoji: '🎸',
    category: 'Кино и музыка',
    question: 'Любимый жанр музыки:',
    optionA: 'Рок и инди',
    optionB: 'Поп и танцевальное',
    image: '/images/questions/q173.jpg',
  },
  {
    emoji: '🎤',
    category: 'Кино и музыка',
    question: 'Концерт любимого артиста:',
    optionA: 'Стою в первом ряду',
    optionB: 'На задних местах, чтобы видеть всё',
    image: '/images/questions/q174.jpg',
  },
  {
    emoji: '🎻',
    category: 'Кино и музыка',
    question: 'Опера или мюзикл:',
    optionA: 'Классика — опера и балет',
    optionB: 'Мюзикл — веселее и зрелищнее',
    image: '/images/questions/q175.jpg',
  },
  {
    emoji: '🍿',
    category: 'Кино и музыка',
    question: 'Поход в кино — это...',
    optionA: 'Большая порция попкорна',
    optionB: 'Без еды, только фильм',
    image: '/images/questions/q176.jpg',
  },
  {
    emoji: '📽️',
    category: 'Кино и музыка',
    question: 'Один и тот же фильм:',
    optionA: 'Пересматриваю любимые годами',
    optionB: 'Только новинки, скучно повторять',
    image: '/images/questions/q177.jpg',
  },
  {
    emoji: '🎙️',
    category: 'Кино и музыка',
    question: 'Подкасты в дороге:',
    optionA: 'Слушаю каждый день',
    optionB: 'Лучше музыку или тишину',
    image: '/images/questions/q178.jpg',
  },
  {
    emoji: '🎼',
    category: 'Кино и музыка',
    question: 'Музыкальный инструмент:',
    optionA: 'Играю или играл когда-то',
    optionB: 'Только слушаю',
    image: '/images/questions/q179.jpg',
  },

  // --- 19. Философия жизни ---
  {
    emoji: '🕰️',
    category: 'Философия жизни',
    question: 'Жизнь — это...',
    optionA: 'Путешествие, наслаждаемся процессом',
    optionB: 'Задача, надо её решить',
    image: '/images/questions/q180.jpg',
  },
  {
    emoji: '🎯',
    category: 'Философия жизни',
    question: 'Что важнее в жизни?',
    optionA: 'Свобода и независимость',
    optionB: 'Безопасность и стабильность',
    image: '/images/questions/q181.jpg',
  },
  {
    emoji: '💡',
    category: 'Философия жизни',
    question: 'Главная ценность для тебя:',
    optionA: 'Время и впечатления',
    optionB: 'Достижения и наследие',
    image: '/images/questions/q182.jpg',
  },
  {
    emoji: '🌱',
    category: 'Философия жизни',
    question: 'Жить надо...',
    optionA: 'Здесь и сейчас, без отложек',
    optionB: 'С прицелом на будущее',
    image: '/images/questions/q183.jpg',
  },
  {
    emoji: '🤲',
    category: 'Философия жизни',
    question: 'Помогать другим:',
    optionA: 'Бескорыстно, чем чаще тем лучше',
    optionB: 'Когда могу и хочу',
    image: '/images/questions/q184.jpg',
  },
  {
    emoji: '⚖️',
    category: 'Философия жизни',
    question: 'Справедливость или милосердие:',
    optionA: 'Справедливость превыше всего',
    optionB: 'Милосердие важнее',
    image: '/images/questions/q185.jpg',
  },
  {
    emoji: '🌌',
    category: 'Философия жизни',
    question: 'Есть ли судьба?',
    optionA: 'Всё предопределено',
    optionB: 'Мы сами творцы своей жизни',
    image: '/images/questions/q186.jpg',
  },
  {
    emoji: '🧘',
    category: 'Философия жизни',
    question: 'Счастье — это...',
    optionA: 'Маленькие моменты каждый день',
    optionB: 'Большие победы и достижения',
    image: '/images/questions/q187.jpg',
  },
  {
    emoji: '📜',
    category: 'Философия жизни',
    question: 'Что бы оставил после себя?',
    optionA: 'Память в сердцах близких',
    optionB: 'Что-то великое для мира',
    image: '/images/questions/q188.jpg',
  },
  {
    emoji: '🪞',
    category: 'Философия жизни',
    question: 'Самокритика в тебе:',
    optionA: 'Сильная, постоянно анализирую',
    optionB: 'Минимальная, принимаю себя',
    image: '/images/questions/q189.jpg',
  },

  // --- 20. Парные ситуации ---
  {
    emoji: '💬',
    category: 'Парные ситуации',
    question: 'Партнёр пришёл уставший — ты:',
    optionA: 'Молча обнимаю и даю отдохнуть',
    optionB: 'Расспрашиваю, что случилось',
    image: '/images/questions/q190.jpg',
  },
  {
    emoji: '🧦',
    category: 'Парные ситуации',
    question: 'Носки разбросаны по дому:',
    optionA: 'Молча соберу, потом поговорим',
    optionB: 'Сразу скажу — собирай!',
    image: '/images/questions/q191.jpg',
  },
  {
    emoji: '📱',
    category: 'Парные ситуации',
    question: 'Можно ли смотреть телефон партнёра?',
    optionA: 'Никогда, это личное',
    optionB: 'У нас нет тайн друг от друга',
    image: '/images/questions/q192.jpg',
  },
  {
    emoji: '🗺️',
    category: 'Парные ситуации',
    question: 'Заблудились в новом городе:',
    optionA: 'Спросим у прохожих',
    optionB: 'Откроем карту в телефоне',
    image: '/images/questions/q193.jpg',
  },
  {
    emoji: '🎁',
    category: 'Парные ситуации',
    question: 'Подарок на годовщину:',
    optionA: 'Продумываю за месяцы заранее',
    optionB: 'Иду в последний день в магазин',
    image: '/images/questions/q194.jpg',
  },
  {
    emoji: '🍝',
    category: 'Парные ситуации',
    question: 'Готовите ужин — кто ведущий?',
    optionA: 'Я главный шеф, ты помогаешь',
    optionB: 'Делаем поровну',
    image: '/images/questions/q195.jpg',
  },
  {
    emoji: '💼',
    category: 'Парные ситуации',
    question: 'Партнёру предложили работу в другой стране:',
    optionA: 'Поеду без раздумий',
    optionB: 'Это долгий разговор',
    image: '/images/questions/q196.jpg',
  },
  {
    emoji: '🛍️',
    category: 'Парные ситуации',
    question: 'Партнёр купил странную дорогую вещь:',
    optionA: 'Это его деньги, пусть радуется',
    optionB: 'Обсудим, нужно ли это',
    image: '/images/questions/q197.jpg',
  },
  {
    emoji: '🤐',
    category: 'Парные ситуации',
    question: 'Поссорились — кто мирится первым?',
    optionA: 'Я, всегда иду навстречу',
    optionB: 'Жду шага от партнёра',
    image: '/images/questions/q198.jpg',
  },
  {
    emoji: '🛌',
    category: 'Парные ситуации',
    question: 'Делите одеяло:',
    optionA: 'Одно большое на двоих',
    optionB: 'Каждому своё, так удобнее',
    image: '/images/questions/q199.jpg',
  },
]

export function shuffle(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export function randomIndices(n, total) {
  return shuffle(Array.from({ length: total }, (_, i) => i)).slice(0, n)
}
